### ISSUE TITLE
Force Picochess to make alternative move from book

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#100]
I often want to practice against a particular opening, i. e. Smith Morra Gambit, but the machine usually declines it in the book. I usually take back my move and make it again, forcing the machine to make a move again and after few attempts I can force it to accept the gambit.

It would be very handy if there was a way to force Picochess to choose an alternative move via clock buttons. This would also help avoiding playing the same old lines against the machine.

Here's an example of my problem (I shot the video to demo a small unrelated bug):

https://youtu.be/zV6YYvuqfoQ

**Comment by LocutusOfPenguin** [comment]
concerning your "gambit stuff":
first, #99 already saying, i want to implement something like "alternative move". I'm happy, you wish it so much as me.

second: for the time until this development is ready: You can change to observe mode, and play the book moves you want to train yourself and then switch back to play move (like after nxc3). As a workaround for the moment.

**Comment by LocutusOfPenguin** [comment]
v0.53 focus on this issue.
Not only on opening book, its working in general (with middle button)
