### ISSUE TITLE
Display warning when entering wrong or illegal move

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#101]
I see novices (children) being confused when they execute a wrong move on behalf of the engine (i. e. moving the wrong knight to c6 instead of f6) as Picochess shows no reaction. I would be nice to display a "wrong move" warning in this case.

Similar warning would be welcome when user executes an illegal move.

**Comment by LocutusOfPenguin** [comment]
Is there a difference to #76  (and my comment there)?

Its useful. The only problem i see is:
How to find out if the player wants to takeback? In this case alot of beeps are coming.

**Comment by ifekali** [comment]
I think a warning of illegal move is welcome in all modes.

> On 18. jun. 2015, at 13.00, Jürgen Précour <notifications@github.com> wrote:
> 
> Is there a difference to #76 (and my comment there)?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
I'm about to close this ticket.
The request is good...but i think, can't be implemented very easily with the hardware as it is.

**Comment by pablo2000** [comment]
Yep... I agree. This should be closed.
