### ISSUE TITLE
Release waiting for some testing

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#107]
Hello,
I'm sorry, but my testing time with a board is very much limited => help needed
I prepared a new release (on my master fork), which i want to merge on monday.
After that working on #101 ;-)

Following bugs & features i fixed/improved:
- Keyboard / More commands (like new game, setup). Mainly for my (nonboard) testing ;-)
- PGN #90, #15 / server&normal mode now similar. Option to give an username at ini/startup for the pgn file (if not, the old system with email/player name working)
- New game / now in wait mode (i don't like something automatically). Press middle or move now.
- Setup Pos. / illegal pos gives error message; reversed mode changed (Button2) should work now

You can help me:
Please test it out. I'm especially interested in bugs which weren't there in old version (0.44), not so much in NEW features (my goal is: "make it stable for release").

If you find too many bugs, i will postpone the merge (hopefully not).
Thanks

**Comment by ifekali** [comment]
Playing as Black is broken now. When lifting the black king (commanding picochess to make first move as White) the clock beeps and displays "New game", but then halts.

**Comment by djdekker** [comment]
Playing Black isn't broken. In fact, after lifting the black king you need to press the middle button to start the game. No automatic starting anymore -- I like that. :)

**Comment by ifekali** [comment]
I don't think this is a good feature, why press a button when there is no need? I think this is a step back in functionality ...

> On 27. jun. 2015, at 14.35, DJ Dekker <notifications@github.com> wrote:
> 
> Playing Black isn't broken. In fact, after lifting the black king you need to press the middle button to start the game. No automatic starting anymore -- I like that. :)
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
hi
phone company broke my inet

y both right - what jonas found was NOT what i wanted. lifting the king is the decision;-) ill will fix it - no idea when see 1st sentence

on the other hand - as said - i like wait - so basically dj is right but in this special situation is double decide

**Comment by puba** [comment]
Lets make a referendum, majority wins

**Comment by ifekali** [comment]
Jokes don't help.

> On 27. jun. 2015, at 17.21, puba <notifications@github.com> wrote:
> 
> Lets make a referendum, majority wins
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
no board & (real) iNet...but i tried to fix the "king lift-bug".

During code review, i thinked, this "king lift" feature should be disabled/deleted.
It's:
- possible by middle button (everywhere instead of only at startpos)
- only useful in game mode
- only black king lift is really of use

**Comment by ifekali** [comment]
So in starting position user would simply press Play and computer would start as White? I could live with that ...

> On 27. jun. 2015, at 21.38, Jürgen Précour <notifications@github.com> wrote:
> 
> 	• only black king lift is really of use
> 

Well, when user wants to play next game as White (after he loses with Black), he lifts the white king to indicate he intends to play with White now.

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
But its in wait state. Then just move (as white).

That was the problem with the old way. Picochess moving, and i had to bring it to a state where i wanted to play white

**Comment by ifekali** [comment]
> On 27. jun. 2015, at 22.10, Jürgen Précour <notifications@github.com> wrote:
> 
> But its in wait state. Then just move (as white).
> 

Ok, sounds reasonable.

> That was the problem with the old way. Picochess moving, and i had to bring it to a state where i wanted to play white
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by djdekker** [comment]
This version largely works fine! :) Thank you Jürgen!

1. Ran into a strange bug yesterday, which I couldn't seem to reproduce. The board orientation was wrong. I'll see if this bug will raise its ugly head again today.
2. It seems that setting the side to move and the board orientation have to be performed in a certain order: first press button 0 (left), then button 1 (second), then the middle button to get computer started. Is this intentional?
3. In the web server the level is now being indicated after the engine name; could it be so in the pgn file, too?

**Comment by puba** [comment]
Mine also working fine, the pico thinking time maybe somehow long, but this is probably due to the fact, that I am using 1.st generation of raspberrypi board for this testing.

**Comment by LocutusOfPenguin** [comment]
djdekker
2 - no / order of button 1; 2 shouldnt matter / button 3 ends! setup thats the last step
3 - both Server&normal pgn should obey names and behave same (even now)

both i will take a look (later)

puba
this problem exists for long already and dj made some new issue&video - i also have it

**Comment by ifekali** [comment]
I think I reproduced it, wrong orientation, see the video (it's probably due to my using reversed board, with USB connector away from me):

https://youtu.be/eOUjHPWQAlI

Machine is confused, wants me to move the BLACK knight to what it thinks it's c3 (but is actually f6 from my perspective).



> On 28. jun. 2015, at 10.19, DJ Dekker <notifications@github.com> wrote:
> 
> 	• Ran into a strange bug yesterday, which I couldn't seem to reproduce. The board orientation was wrong. I'll see if this bug will raise its ugly head again today.
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by djdekker** [comment]
I found a minor bug in the game notation:

if a game starts from a custom position with Black to move, then the move number "1" is not printed in the pgn output. For example: "e5 2. d5 Nc4 3. Re2 Nd6" instead of: "1... e5 2. d5 Nc4 3. Re2 Nd6".

The string "1... " should have been added before the first move.

**Comment by LocutusOfPenguin** [comment]
thx ifekali
easy to reproduce error due to video!
Prob. machine wants to play Nf6, but displaying Nc3 (wild guess!)... also the clock rotation is not correct. Perhaps same error inside.
If i cant fix such things until tomorrow (today i'm almost blocked), i will for sure NOT merge it.

And just another error...But i like it...both easy to reproduce...But i hate it, making errors ;-)
THANKS

**Comment by ifekali** [comment]
Yes, machine wants to play black knight to f6 (from my point of view), but internal orientation is wrong, so it displays Nc3 (which is of course never possible with Black).

If I move the black knight to f6, it will accept the move.

> On 28. jun. 2015, at 14.06, Jürgen Précour <notifications@github.com> wrote:
> 
> Prob. machine wants to play Nf6, but displaying Nc3 (wild guess!)

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
@djdekker 
small update
with the missing "1." in pgn (b moves first)
I think that's an issue for the lib we are using (=python chess). I made an issue there. Lets see what the owner saying.

**Comment by LocutusOfPenguin** [comment]
new push.
niklasf repaired his lib, and i (hopefully) repaired the rotation bug in setup.
In this case, this issue is closed.

**Comment by ifekali** [comment]
Looks  good to me.

**Comment by puba** [comment]
Well, my board has USB and clock plugs on the left side of the board, so the press on button2 when in position setup mode is necessary...everything else working fine, congrats

**Comment by LocutusOfPenguin** [comment]
@puba 
i meant, its normally not needed. You can turn around as you want.  Also pressing twice or more no problem.
