### ISSUE TITLE
Clock flashes 'OK' while computer thinks

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#109]
This is happening a lot: while the computer is thinking, the clock flashes 'OK' once for no obvious reason. It does not happen before *every* computer move, but rather randomly, as it seems.

Short videoclip illustrating this issue:
http://youtu.be/cpqaHQlR3qQ (you can see the superfluous 'OK' at 0:09).

**Comment by LocutusOfPenguin** [comment]
That's also a long time bug. Basically cause i can't stop the search in game mode. Here i have to wait for niklasf to do something at his lib (which we are using). Also in contact with him (& shiv).

For this, and #108 , you might try the newest version, and give feedback  pls.

**Comment by djdekker** [comment]
In 0.47 the clock is still flashing 'OK' a lot. It does not seem to have become less frequent.

**Comment by LocutusOfPenguin** [comment]
i know, there are some issues with "ok" , "new game", "book" ,, and so on.
But now, i wont fix it..cause i need all this stuff, for finding the basic problems behind.
Please see my comments on the newest ticket.

**Comment by djdekker** [comment]
Solved in 0.50.
