### ISSUE TITLE
Wrong behaviour when computer's flag falls

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#111]
In a 3 + 2 increment game the computer lost on time against me. I decided to continue the game. From this point onward Picochess showed the following wrong behaviour:

Instead of just displaying the out of time message once, the clock displayed the "TIME" and "0:00" messages after every move I made. Also, after every move of mine the computer emailed an updated pgn version of the game (totaling to some 25 emails!) instead of its usual behaviour -- send an email when the flag falls and, if the user continues, send another email when the user aborts the game or checkmates etc.

**Comment by LocutusOfPenguin** [comment]
Im not using the email feature. But when i continue to play a out of time game, i only get one game in games.pgn (which should mean, one eMail too). The problem still exists for you?

**Comment by djdekker** [comment]
Yes, the problem still exists, but only if the computer runs out of time.

When the human player runs out of time, Picochess behaves correctly.

**Comment by LocutusOfPenguin** [comment]
oh.... i always let MY time run out (for test)

**Comment by djdekker** [comment]
The computer behaves correctly in version 0.50.
