### ISSUE TITLE
Refreshing Web Server Display

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#124]
Two minor issues with the web server in Picochess v0.51:

[1] After changing the engine or the level, the web server display does not show these changes. The display should be refreshed so that it always shows the actual engine name and level.

[2] When the user has placed the pieces back into starting position, the web server is still showing the final position from the previous game. Instead, it should refresh the display and show the pieces in starting position.

**Comment by pablo2000** [comment]
Thanks DJ

I'll take a look at this this evening.

**Comment by pablo2000** [comment]
Hi DJ

Have been through and corrected the missing information. Now the game information area of the web page will show correct engine and level in use. The page will refresh with the next move update. I'm not sure if it's worth forcing a refresh to all clients before the move update, but I guess that's a point for discussion.
In the event it's decided that it should immediately update, I think it may be in Shivs area - although I'm not certain having not looked too far into it.

Pablo

**Comment by djdekker** [comment]
Thanks Pablo. The web server is updated now with correct info about the engine and level.

**Comment by sshivaji** [comment]
Thanks Pablo. I don’t believe in code areas, please change code as you see fit even on the web server! 




I have some updates to the web server html, mainly better PGN output that you can load into chessbase etc. I will merge in my code with whatever the changed version of the web server is.




I dont think we need an update of engine and level before the move update to all clients. This probably is not that common a use case.




Shiv




—
Sent from Mailbox




Hi DJ


Have been through and corrected the missing information. Now the game information area of the web page will show correct engine and level in use. The page will refresh with the next move update. I'm not sure if it's worth forcing a refresh to all clients before the move update, but I guess that's a point for discussion.

In the event it's decided that it should immediately update, I think it may be in Shivs area - although I'm not certain having not looked too far into it.


Pablo
