### ISSUE TITLE
Bring back the beeps

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#127]
Please bring back the confirmation beeps after every action done. This used to be, but was somehow removed this summer.

I wish for a confirmation beep after I (user) make a move (to confirm it's legality) AND after I (user) make a move for the machine (to confirm I did make the right move for the machine). Now the beep is only heard when the machine displays a move.

Without audible confirmations I find myself always checking the display if everything is ok, it's quite annoying.

For users that are bothered by beeps, there should be a setting in .ini.

Pleasepleasepleaseplease ...

**Comment by LocutusOfPenguin** [comment]
your wish is our command, dear Jonas.
It was deactivated cause of timing problems.

**Comment by LocutusOfPenguin** [comment]
I bring back the messages again (but all -- incl. "computer move done").
For me there is no difference if its a comp move, or a user move.

Also updated some clock messages to be more clear.

**Comment by pablo2000** [comment]
Jürgen 

Like Jonas said, could you make this a .ini preference? For me (but not for others) I find this an interruption to my thinking and the flow of the game - I know when I've made a move (and not normally illegal!) and when I've made pico's move correctly the clock restarts - and again, I know the board well enough not to make errors often.

I think this is a love/hate thing. You either love this feature or find it annoying.

Pablo

**Comment by LocutusOfPenguin** [comment]
Pablo

well, i understood Jonas this way that he was speaking about the sound only. And for this, we have a flag already. On #99 i speak about a beep level stuff, but i didn't have the time to implement something (on/off is for me not fine grained enough, but i have more important stuff to do first)

Seems, y want a flag to turn on/off these message (incl. the sound), yes? That's not bad idea and easy to implement.

Jürgen

**Comment by pablo2000** [comment]
Yes that's what I had in mind - and as you say quick and easy to do.

If you're tied up with other stuff, I'll just go ahead and implement a simply on/off from the .ini file.

What are you working on at the moment?

Pablo

**Comment by LocutusOfPenguin** [comment]
Thanks..I did it already ;-)

I'm busy with this "freezing at startup"
and i want to implement "alternative moves" as my next project, but don't find the time for it right now.

Jürgen

**Comment by ifekali** [comment]
Thanks for bringing the beeps back, I love it.

(However, I cannot finish a game on my USB board without a freeze. Bluetooth board seems to work ok)


> On 3. sep. 2015, at 17.56, Jürgen Précour <notifications@github.com> wrote:
> 
> Thanks..I did it already ;-)
> 
> I'm busy with this "freezing at startup"
> and i want to implement "alternative moves" as my next project, but don't find the time for it right now.
> 
> Jürgen
> 
> —
> Reply to this email directly or view it on GitHub.
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by pablo2000** [comment]
Hahaha... I did it too, went out to collect my daughter from school, came back and you'd check it in. That wasted a whole 3 minutes of effort :)

On the freezing thing... if you're considering a timing issue, just as more information I'm using an overclocked Pi2 and WiFi and Bluetooth board/DGT3000 - I've _never_ had a freeze at startup, except for the networking hangs I've previously mentioned.

Pablo

**Comment by sshivaji** [comment]
I think lets disable network by default. I will be able to spend time in
the weekend to fix this properly.

**Comment by pablo2000** [comment]
OK Shiv... I have some time this evening so I'll switch it around a little.

Pablo

**Comment by LocutusOfPenguin** [comment]
ok, took me abit more time as only 3m :-) Therefore i wasn't wasted (even you did it before) ;-)

This morning i had problems with XL clock, before something else, Jonas has other problems.. I wish finally solved, so my beloved "a.m." can finally start, ha!

J.

**Comment by LocutusOfPenguin** [comment]
main thread (beep for ack) is done => close this issue.
