### ISSUE TITLE
What is the default opening book?

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#128]
According to the docs, the default opening book is varied.bin. But according to picochess.py it is gm1950.bin.

Does anyone prefer either book? I have a slight preference for varied.bin, but gm1950.bin (although very large) is ok with me.

**Comment by sshivaji** [comment]
I like GM1950 because of recent GM games :)




Shiv


—

**Comment by pablo2000** [comment]
I had been thinking about making the default opening book an option from the .ini file.

Any thoughts?

Pablo

**Comment by sshivaji** [comment]
Sure, we can do that. Varied.bin by default is ok.
