### ISSUE TITLE
Book name not shown at clock

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#130]
Using the queen, doesn't show the name of book in display anymore.

**Comment by LocutusOfPenguin** [comment]
not belong to this issue (but i dont know, what exactly i did - just play around with the buttons).

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'int' object is not callable

**Comment by pablo2000** [comment]
Sorry. This crept in when I was suppressing the extra book display, rather than just 'Ok' or 'Ok book' as it now is.
