### ISSUE TITLE
select engine

### ISSUE THREAD

**Issue by lionping** [jromang/picochess#132]
in picochess-0.51 I've tried to select  through the menue (dgt3000-clck) an engine, but  picochess *freezes* with the exception 
picochess-0.51a/dgtdisplay.py", line 210, in process_button0
    HardwareDisplay.show(Dgt.DISPLAY_TEXT, text=(self.installed_engines[self.engine_index])[1], xl=None, beep=BeepLevel.CONFIG)
IndexError: list index out of range

**Comment by lionping** [comment]
After downloading latest changes --> It's not working yet! so keep #70 open!

selecting "engine" on *clock*menue

then pressing button1 throws the exception "IndexError:..." 

after picochess-restart, selecting menue 'engine' again, presing button2 to select engine just outputs a warning, that the name is too long for the dgt3000-display
2015-09-03 11:13:22.59 WARNING dgthardware - _display_on_dgt_3000: DGT 3000 clock message too long [stockfish_human]

but

pressing button3 on dgt3000-clock to confirm selected engine throws the following exception:

2015-09-03 11:35:31.832 ERROR uci - __init__: OS error in starting engine
Traceback (most recent call last):
  File "/home/itsme/picochess-0.51a/uci.py", line 101, in __init__
    self.engine = chess.uci.popen_engine(path)
  File "./libs/chess/uci.py", line 1321, in popen_engine
    return engine_cls(process)
  File "./libs/chess/uci.py", line 479, in __init__
    self.process.spawn(self)
  File "./libs/chess/uci.py", line 347, in spawn
    self.process = subprocess.Popen(self.command, stdout=subprocess.PIPE, stdin=subprocess.PIPE, bufsize=1, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "./picochess.py", line 619, in <module>
    main()
  File "./picochess.py", line 435, in main
    engine_name = engine.get().name
  File "/home/itsme/picochess-0.51a/uci.py", line 115, in get
    return self.engine
AttributeError: 'Engine' object has no attribute 'engine'

thx a lot for ALL YOUR FIXES!!

**Comment by pablo2000** [comment]
Hi

Can you tell me how many engines you have installed, which is the default and which you are trying to load

**Comment by pablo2000** [comment]
Pls could you try rename your engine files to be 8 characters or less, as in the instructions. e.g. stockfish_human -> Human

**Comment by LocutusOfPenguin** [comment]
"After downloading latest changes --> It's not working yet! so keep #70 open!"

This has nothing to do with #70. Why y saying so?

**Comment by lionping** [comment]
for testing-purposes I'm just using stockfish and stockfish-human (overtaken from picochess-0.45 image for raspberry2

ok -
default engine is stockfish
and yeah - I renamed stockfish_human to human but it down'nt change the behaviour in engine-menue

and sorry, LocutusOfPenguin, I've mixed up the issues ;-)

**Comment by lionping** [comment]
can you reproduce this behaviour? sounds like you haven't observed this engine-menue-bahaviour yet

**Comment by LocutusOfPenguin** [comment]
Could it be that the engine file is in wrong binary format? Just my 1cent ;-)

**Comment by pablo2000** [comment]
no... I know the problem

You have picochess installed in a different directory to /opt/picochess but in your picochess.ini you have the engine= parameter set to something like "engine = engines/stockfish".

As you are running from a non-standard installation, you must use the full path for the engine parameter.

Change the setting to "engine = /home/itsme/picochess-0.51a/engines/stockfish" and everything will work. There are other problems you've instroduced by using a 'custom' installation without setting full paths in the ini file - but I'll not bore you with them.

BTW, if the "thx a lot for ALL YOUR FIXES!!" was genuine, you're welcome. If it was sarcasm (which is how it reads), you understand we do this on our own time as volunteers, and we really do test this stuff (in it's normal installation), don't you.

Pablo

**Comment by pablo2000** [comment]
Also, Jürgen...
I've added a 'fix' to trap this situation and will included it in my next bug fix push.

P

**Comment by pablo2000** [comment]
Folks

Sorry, that's a little unclear, now I've re-read it. The key points are, at the moment:
1) Any installed engines must be in one folder
2) The folder should be named 'engines'
3) The engines folder should be a subdirectory of the picochess installation
4) The .ini file should include a full path to the default engine.

HOWEVER, I have just implemented a change so that: 1 and 4 must still be true, but the others are not important. Engines can be anywhere, as long as they are all together if you want them to appear in the menu.

**Comment by lionping** [comment]
after having much fun with my family i'm finally back and have read your posts and tested the 052-version
LocutusOfPenguin was right - i haven't checked that the picochess-image for my new raspberry2 is still a 32-bit and not (as automatifcally thught) a 64bit system; what a dummy mistake
so indeed - the copied stockfish[_home] binaries from the raspi-image to my linuxmint17 were the reason, why engine-select on dgt3000-clock hasn't worked;
BUT I could play games, set a position and play from there or activated analyze-mode without any problems, because on linuxmint17 /usr/games/stockfish was used when I started picochess.py (/usr/games is part of my $PATH)

on the rsspi2 (picochess-0.51) everything was working smoothly with some small exceptions (sometimes picochess freezes when you takeback a move - but that is maybe a story for another issue) -
and on the raspi. when I wanted to check what engine was currently loaded picochess was freezing whenever I tried that; engine-selectin on raspi was working bt when I presssed the 3rd button to confirm my selection picochess was also freezing to death (maybe because stockfish_home had more than 8chars.

picochess-0.52 is now only working properly when I enter the absoute-path to the stockfish-binary in picochess-0.52/engines on my notebook.

but if I comment engine = /home/itsme/picochess-0.52/engines/stockfish in picochess.ini and start picochess from within picochess-0.52/ like

./picochess.py -d /dev/ttyACM0 -dgt3000 -e stockfish
than it crashes with
  File "/home/itsme/picochess-0.52/utilities.py", line 405, in get_installed_engines
    engine_list = sorted(os.listdir(engine_path), key=str.lower)
FileNotFoundError: [Errno 2] No such file or directory: 'stockfish

ah ok - so I had to start picochess from within picochess-5.52 also with the absolute or relative path to stockfish and then it was working properly

for testing-purposes I've tried to copy /usr/games/gnuchess to the engines/-folder, and it appears in engines-select, but when I confirm the selection picochess is freezing without throwing any exception!

and sorry gues for the fuzz i've caused and for these many many lines ;-)
next i'm going to test picochess-0.52 on the raspberrypi2

**Comment by lionping** [comment]
with pico 0.52 the freeze of picochess running on raspberry2 vanished, when asking directly after start through the engine-menue, "what engine is currently loaded" by pressing Button1

I've tried several engines to run with picochess and so far, "glaurung" and "fruit" were the only one, where after selection (Button2) and confirmation (Button3) picochess hasn't turned into a kind of "stand still"-state, where after pressing another button nothing's seems to go on - looks like picochess was frozen...

in the logfile (loglevel debug) there aren't any warning/error-whatsoever messages -
And I've observed, that in this state where it seems that the clock doesn't notice any button-presses (Display remains unchanged) - but in the logfile there are the button-presses recorded!

In my opinion you have solved the engine-selection issue -
Is there a list of engines running properly with picochess?
If not could you initiate one in the docu/usage?

gnuchessu (trailing u for uci) doesn't work

and thx a lot for this wonderful picochess-training-tool !!

**Comment by pablo2000** [comment]
Hi again

As of today (pending being moved to master), I've improved the error handling if a new engine fails to start properly - rather than hang, the system now reports an error on the clock and properly falls back and reloads the last working engine.

I have the following engines running OK, but I too have found a lot that don't, but I cant get suitable source to rebuild them. Working are:

Cinnamon
Fruit 2.1
GreKo 9.8
GreKo 12.5  (plays like a mad man!)
Human
Stockfish
Toga II
Zurichess

But those are just the ones I have and am using to test engine swaps. DJ put out a tarball with lots of engine recently, via the forum, but I found a number of those didn't work on my Pi2.

Pablo

P.S. if you're using it as a training tool, be sure to check out 'unlimited books' - I use that for tournament preparation (or a specific opponent). I make a new book with the opening lines I particularly want to work on (I'm on the old Benoni at the mo, as most players only know the modern) and can practice just those lines - there's a tool to take databases of pgns and create a polyglot book.

P.P.S. Also up soon, there will be a new 'Blunder Watch' feature to alert you to questionable moves, with configurable blunder threshold.

**Comment by LocutusOfPenguin** [comment]
Great! Thanks, Pablo

**Comment by lionping** [comment]
Thank you very much, Pablo!
I'm thrilled with all these many possibilities
creating my personal training-opening-book is a project I'm going to start soon - have first to get all tools and knowledge together.
but this is stuff for the forum ;-)
thx a lot
MichaelZZ

**Comment by djdekker** [comment]
Thanks a lot, Pablo, for all your recent contributions to Picochess! It's really fun to play against different engines and switch between them easily. The idea of unlimited opening books is also exciting.

I'm sorry to read that you haven't got all engines running. Except for GNUChess 6.1.2 the engines are running fine here, probably because all the required developer tools are also installed. I can upload a zipped image of my Raspberry Pi 2 (SD card size is 16 GB) later today for anyone who is interested. It should run on any Raspberry Pi 2, though not on Raspberry Pi B.

**Comment by sshivaji** [comment]
Very nice work, Pablo!

I will finally be able to spend some time coding and testing this weekend. Would be great to package all these engines in an updated image.

It would be good to put oat least one engine that plays like an amateur, do any of these engines have less the say 2400 elo?

Shiv

**Comment by djdekker** [comment]
Here is a link to my compressed Picochess 0.52 image file for Raspberry Pi 2. It expands to a 16 GB disk image. Unfortunately, I don't (yet) know how to shrink a partition on RPi2, which would allow for a smaller image file.

The disk image contains Picochess 0.52 with the following engines: Arasan 18.0, Cinnamon 1.2c, GNUChess 6.2.1, GreKo 12.9, Hakkapeliitta 3.0, Maverick 0.6, Sayuri 2015.08.12, Senpai 1.0, Stockfish 6, Stockfish 150215, Stockfish Human, Texel 1.05, Toga II 1.3.1 (executable name: 'fruit'), Zurichess Fribourg.

Engines that play under 2400 Elo are Cinnamon and Sayuri, probably also GreKo, Maverick and Zurichess.

The image also contains Scid vs. PC 4.14.

https://drive.google.com/file/d/0B9qWkOu8LbC8bjhZM0tjbkVTR0U/view?usp=sharing

**Comment by LocutusOfPenguin** [comment]
on my laptop (so Intel),  i tried the following 4 engines:
Hakkapeliitta, Cinnamon not working
GreKo,Arasan working

just "make" and install. "Hakkapeliitta" crushing at beginning, "Cinnamon", when first nonbook move.

**Comment by pablo2000** [comment]
Hey Jürgen

I presume you tried running just the engines from the command line? Same behaviour?

I had a similar problem with Senpai as you have with Cinnamon - even from the command line, it would start, respond to the first 'uci' command but die after a 'newgame'... I tracked it as far as establishing it to be a problem when it was allocating memory for the hash, but havent had time to get any further. I'm guessing it's a memory model issue (??) of some kind.

**Comment by LocutusOfPenguin** [comment]
Well, as a former C-dev... i dont understand why their sources producing complie-warnings..anyway:
Starting by command line:

Hakkapeliitta 3.0 (C) 2013-2015 Mikko Aarnos
Detected 8 CPU core(s)
Detected hardware POPCNT
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Abgebrochen (Speicherabzug geschrieben)

=> total fail :-(


With Cinnamon:
i can send uci commands, and it seems to work on command line.

Test futher anyway.

**Comment by pablo2000** [comment]
Ahhh. The first is a linker problem pulling in pthread. You must specify "-pthread" both when you compile AND link: as in ......-o wibble -pthread ....... The order is important and must be the first option afte specifying the output file.

**Comment by LocutusOfPenguin** [comment]
sorry?
Anyway, i opened an issue at his github.

**Comment by pablo2000** [comment]
:)

For Hakkapeliitta, I was pointing out a common problem when using the threading library. It's platform dependent so may not be in his Makefile (or may be one of the build options inside it). I have had the problem, with that exact error message before.

Anyway, you opened an issue, so hopefully he'll respond soon.

**Comment by LocutusOfPenguin** [comment]
ok...found out myself.
https://github.com/mAarnos/Hakkapeliitta/issues/2

**Comment by LocutusOfPenguin** [comment]
On Hakkapeliitta is a bug. Its already repaired (both from aarnon & niklasf). But for using this engine, we must have the latest version (python-chess-lib dont need to be updated, since one time repair is enough for the moment)
