### ISSUE TITLE
Bluetooth connection issue

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#145]
Thank you for your quick replies.
I have another small but persistent problem with me DGT_BT_eBoard and picochess 0.55:
USB connection (ttyACM0)works as it should - But Bluetooth needs attention.

Directly after boot I I always have to start picochess twice when using a bluetooth connection. The first time picochess beeps (no version message) and says new game but freezes (waits for  ???). There are no errors in the log file. I must stop picochess using the init script as sudo and start again. Picochess comes up beep beep new game. ok.

If picochess had started once all next times are ok. This problem only occurs for the first start of picochess after boot.

I checked the connection with hcitool and rfcomm. rfcbind all does not help. 
Apparently "rfcomm -a" gives three channel states ("clean!", "ttyattached" and "closed"). "Clean" is directly after boot. "ttyattached" is after the first (unsucessful) call of picochess. "closed" is after stop of picochess.

Once the channel state has changed from "clean" to "ttyattached" or "closed" Picochess successfully starts if the channel is close or attached.

Any idea how to fix this?

Kind regards

Laterunner

**Comment by pablo2000** [comment]
This is a bit puzzling.... please could you try something - I'm not certain we will learn anything from it, but maybe.
1) Prevent picochess service starting at boot - 
        "sudo nano /etc/init.d/picochess"
         Find the line (should be 33) that says screen -dmUS.... and place a # at the start, Ctrl-o, Ctrl-x
2) Reboot - "sudo reboot" or "sudo shutdown -r now", depending on your distro
3) After reboot, check bluetooth state then start picochess manually - 
           "rfcomm -a" ....does this say clean?
          "cd /opt/picochess"
           "sudo ./picochess.py -d /dev/rfcomm0 -e engines/stockfish"
4) Look for diagnostic messages being printed - I would expect to see a bunch of messages about the speech/audio, but just see if there's anything else.
5) You can exit from picochess with Ctrl-z, then re-edit the picochess file as above and remove the #, then reboot again.

It's a bit odd, as the Bluetooth is the most stable and reliable connection type we've found generally, especially with the Pi's (I know you're on odroid btw). Let us know if you find anything.

**Comment by djdekker** [comment]
I think the `pico_dgt_bt.sh` script needs some rewriting.

This script is calling `bluez-simple-agent` to setup the Bluetooth device -- which was appropriate in Raspbian Wheezy -- but should rather be calling `bluetoothctl` (or shouldn't it?) in later operating systems like Raspbian Jessie or Ubuntu 15.10.

I have been trying to start Picochess on a headless RPi2 running the latest Ubuntu 15.10, but without success. When not running headless, Picochess 0.55 starts fine after first making the Bluetooth connection manually (Bluetooth Manager) and then starting `picochess.py` from the command line.

**Comment by Laterunner** [comment]
To Pablo:
thank you for your reply, on my system I always start picochess manually, either I always call the script manually.  First I change to /opt/picochess  than I either  call "/etc/init.d/picochess.init start|stop" or I start with "python3 picochess.py -d /dev/rfcomm0". Both give the identical result.

As I mentioned above: after boot "rfcomm -a" ---> channel 1 is clean, afte one run channel 1 is attached after stop channel 1 is closed. Picochess starts up correctly with channel 1 attached or closed

Kind regards Laterunner

To DjDekker:
I think you describe just exactly what I tried to describe above: Picochess starts, connects to bluetooth, beeps once, says newgame and than waits something whatever. - the prog must be killed once (by script or Crl-c. The next starts are ok. 

A nasty problem ... I do not think that the problem is in "pico_dgt_bt_sh". I suspect the main program  or something that is called after starting the main program. If I find some time I try to debug

KInd regards Laterunner

**Comment by pablo2000** [comment]
Ok. Good feedback. I also think your problem does not come from pico_dgt_bt, although that may well need looking at again now - but that is only used for discovery. 

So here's the thing. Pico itself cannot tell whether you've started the program before or not (or a hundred times even), it simply deals with a virtual comm port in /dev. If it 'starts' but only gives one beep it sounds like the bt comms have stopped working. You should always get three beeps, if the board is in a starting position. One when pico begins to initialise, one when it finishes initialising and shows version etc, then a third when the new game is announced. But if the clock display is switching to show a new game, there is a connection to the board of some sort - so it's very puzzling really. 

Definitely nothing useful or odd looking in picochess.log??

**Comment by Laterunner** [comment]
to Pablo2000
I think you understood my problem:
"rfcomm -a" or "hcitool con" might help to find out what is wrong
in short - after fresh boot of ubuntu 14.04.3 LTS:
--------------------------
1. rfcomm -a xxxxxxx channel 1 clean      ## I think this must be the clue
2. hcitool con: empty ## also a clue
--------------------------
3. the first time I start picochess from command line (I am in /opt/picochess)
4. one beep
5. no display change on the DGT3000 (in mode 25)
6. short audio output "new game"
7. nothing more - I stop picochess with ctrl-c
---------------------------------------------
but now
8. rfcomm -a xxxxxx channel 1 [tty-attached]
9. hcitool 
---------------------------------------------
10. picochess can be successfully started from the command line 
Beep Beep - 
Display shows "Pico 0.55"
Display shows "new game"
audio "new game" voice from Marvin
beep
## everyting ok 

again the same happens if I start with the script in /etc/init.d
after stop and a second start picochess is alive
- must be something with my Bluetooth settings at startup
- maybe with the bluetooth daemon ## i try more research
Kind regards Laterunner

**Comment by Laterunner** [comment]
One more thing I the logfile (errorlevel warning) I find this:
2015-10-27 12:53:23.102 WARNING dgtserial - process_message: DGT message not handled : [DgtMsg.DGT_MSG_SERIALNR]

I think this might have something to do with the start stop start problem
hope that someone is still trying to look at this problem

Kind regards
Laterunner

**Comment by pablo2000** [comment]
Can you check whether this message appears in your log when you have a successful startup.
How old is your board?
I have checked all my test setups and been through the code and there's no point that I can see the serial number being requested, and certainly there's no specific code to handle it. The log message itself is not necessarily a problem, however as it appears never to be requested, and looking at the bit patterns of the ones that are, it could potentially be a bit corruption in the serial link - perhaps a driver issue. Not sure at this point.

**Comment by LocutusOfPenguin** [comment]
Strange!
As pablo said, this message code is NOT used (at all).

I can only IMAGE, that the serial port sends strange values and the software gets this message_id, even the bytes should be ignored.
Perhaps the line before this error ("<- DGT [%s], length: %i") tells us something - esp. the length value.

**Comment by Laterunner** [comment]
To Pablo and Jürgen,
back again ...
But
Board Serial Number  0000 21630
Board Version 3.1
Clock Version 2.2
Firmware 3.01 191 213/Bootloader 3.01
The startup only occurs if starte the first time after boot
I receive only one beep from the clock and audio "new game" than freeze
I kill  the screen (1 socket wiped out)
start again and everything is alright

Actually each time picochess starts the first time and fails there are two warnings in the logfile
coming shortly after each other. Later there are no more warnings.

2015-10-27 18:02:31.545 WARNING dgtserial - process_message: DGT message not handled : [DgtMsg.DGT_MSG_SERIALNR]
2015-10-27 18:02:31.884 WARNING dgtserial - process_message: DGT message not handled : [DgtMsg.DGT_MSG_SERIALNR]

I triple checked my picochess.ini and also replaced the picochess.init with an untouched one
the problem remains grrrrrrrrrrrr

still I don't want to give up
maybe you can have another look at the code.
there must be something causing this behavior
 kind regards

laterunner

**Comment by sshivaji** [comment]
Great that we are close. Are you using Odroid-xu4 (I can try to debug on
the device)? i have one of these now.

**Comment by Laterunner** [comment]
Dear sshivaji
DGT_MSG_SERIALNR 
I can find this string in uttilities.py line 239 and 312
yes I have odroid XU4 with Ubuntu 14.04 LTS

Kind regards

Laterunner

**Comment by sshivaji** [comment]
Can you create an image and upload it? I can provide a server if you need.

Shiv

**Comment by Laterunner** [comment]
Hi shiv, I am new in linux and odroid. I installed Lubuntu from image provided by Hardkernel to an 8GB EMMC Card, updated ubuntu and installed picochess from the scratch following exactly the decription for picochess 051. 

I know how to put the image onto the emmc, but I do not know how to create an image of the emmc yet. I studied the forum at hardkernel, but there seems no easy way to create a bootable image for the odroid. If you give me a hint how to do this. I have OSX and Win 7 to do this.

Kind regards Laterunner

**Comment by puba** [comment]
Hmm, interesting, I am expereencing similar issues on USB connection. On first boot xl clock freezes, on second works normally....

**Comment by djdekker** [comment]
On Ubuntu 15.10 I'm seeing very similar behaviour to what Laterunner is seeing:
1. `sudo /etc/init.d/picochess start` => Bluetooth connects, clock beeps once, no response anymore;
2. press Ctrl-C twice to quit picochess => Bluetooth connection lost;
3. `sudo /etc/init.d/picochess start` => Bluetooth reconnects, clocks beeps three times, playing ok.

I have posted the [picochess log](http://www.djdekker.net/picochess.log.txt).

**Comment by Laterunner** [comment]
Hi DjDekker,
if you put the log level to "warnings", do you also get the two warnings I described above?

Kind regards

Laterunner

**Comment by djdekker** [comment]
Hi Laterunner,
No warnings here.
After setting the debug level to "warning" there are no more messages in picochess.log.
Greetings,
DJ

**Comment by Laterunner** [comment]
to DjDekker 
no errors also the fist time you start and picochess hangs?? I get warnings only than
Kind regards Laterunner

**Comment by djdekker** [comment]
No, none at all...
I'll try again tomorrow and post any warnings that appears in the log.

**Comment by ifekali** [comment]
> On 27. okt. 2015, at 20.11, DJ Dekker <notifications@github.com> wrote:
> 
> On Ubuntu 15.10 I'm seeing very similar behaviour to what Laterunner is seeing:

I'm seeing something similar on my raspberry 2, ubuntu 14, connecting to USB board! No bluetooth!

> 1. sudo /etc/init.d/picochess start => Bluetooth connects, clock beeps once, no response anymore;

Rasbpberry boots up, autostarts picochess, beeps once, no response anymore.

> 2. press Ctrl-C twice to quit picochess => Bluetooth connection lost;
> 3. sudo /etc/init.d/picochess start => Bluetooth reconnects, clocks beeps three times, playing ok.
> 

I ssh to the raspi2 and do:

sudo service picochess stop
sudo service picochess start

and it starts.


- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
> On 27. okt. 2015, at 21.57, Jonas Žnidaršič <jonas@jonas.si> wrote:
> 
> ubuntu 14

Well, I'm not sure what version my ubuntu is, how do I check?

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by djdekker** [comment]
I went back to Picochess version 0.51 (stable), still on Ubuntu 15.10 for RPi2. It makes no difference: still having the same Bluetooth connection problem. And still no warnings in picochess.log when the log level is set to 'warning'.

**Comment by djdekker** [comment]
For what it's worth: going back even further to v0.45 (stable) did not help either.

**Comment by Laterunner** [comment]
To djdekker,
Hi - I shall stay with Version 0.55. 
But you are correct:  I also had the BT startup problem (start-stop-start ) with Version 0.51. At the moment I can live with the BT Problem. I made a simple ./startup script and some simple modifications to "/etc.init.d/picochess.init" to monitor essential things i.e. "rfcomm-a", "hcitool con", "whoami" and "pwd" and case (USB0, rfcomm0, ttyACM0, revelation) this works well for me.

Finally the DGT_BT Board can be connected via USB. Than picochess starts as it should directly after boot. The Board needs charging anyway  ... so actually no extra cable needed
 
If I have some spare time In one or two weeks I will have another look to find out what is wrong :)

Kind regards

Laterunner

**Comment by djdekker** [comment]
Hmmm... as long as I use a vanilla `picochess.ini` (identical to `picochess.ini.example`), PicoChess starts up fine (with three beeps) first time after boot and after manually establishing the Bluetooth connection. This is on RPi2 using Ubuntu MATE 15.10.

But as soon as I change `picochess.ini` (for instance, comment out the `disable-dgt-clock-beep` line) and reboot and reconnect, the single-beep-and-stall issue rears its ugly head. Then Pico needs to be quit and restarted.

**Comment by djdekker** [comment]
The last time the issue occurred was after uncommenting `disable-ok-move`. No problem when only uncommenting `disable-dgt-clock-beep`.

**Comment by Laterunner** [comment]
Dear DjDekker,
I cannot confirm your finding: Uncomenting "disable -ok-move" in .ini does NOT change start-stop-start issue with bluetooth connection. After a fresh boot - picochess has to be started, killed and started again with my odroid xu4 setup.

Cable (USBworks) is ok. 
I was to busy to take another look to the problem yet. 

Kind regards
Laterunner

**Comment by Mercutio111** [comment]
Hi together,

I am sorry, if this in not the right place for me to send a comment about this issue. I am just a newbe to raspberry pi and picochess (and even to Linux / Debian). ;-)

But I have (or should I say "had") the same problem as desribed in issue #145. I solved it unconventionally: I started picochess in any position but the start position (e.g. I put the knights to f3 and f6). Then the display shows the right version (pico 0.55) and when I put the pieces to the right places (g1 and g8) voilà: my dgt xl clock shows "New Game"!

Maybe this can help!

Best regards
Axel (from Germany / Hamburg)

**Comment by Laterunner** [comment]
Hi Axel,
thank you for your comment. I am not sure that you solved the same problem that I have described. Issue 145 is a Bluetooth connection problem:

After Boot - I have to start - stop and - start again picochess to get a bluetooth connection working. Using a non start position for first startup does not change this behavior (I tried your suggestion).

You can check state of the BT connection with "rfcomm -a". - There are three states for the BT channel as I described above: "clean", "tty-attached" and "closed"

After boot the channel is "clean". Picochess will not finish startup,  but the Channel changes to "tty-attched". Now you can stop (kill) picochess. Next start is ok (Beep-Beep-Pico 0.55-Newgame-Beep)

As I described above there is NO PROBLEM if a USB connection is used: Picochess starts immediately as it should.

Kind regards Laterunner

**Comment by Mercutio111** [comment]
Hi Laterunner,

thank you for your kind reply - although I ignored that the mentioned problem is a bluetooth issue ;-).

With bluetooth I now have no problem. I installed:

sudo apt-get install bluez-utils blueman

and after reboot bluetooth connection was successfully established.

When I execute "rfcomm -a" I get: 

rfcomm0: 00:24:AB:00:0C:05 channel 1 connected [tty-attached]

Hope you can solve the bluetooth problem!

Best regards
Axel

**Comment by LocutusOfPenguin** [comment]
Is there anything open?
