### ISSUE TITLE
Move takeback: computer's clock keeps running

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#147]
In PicoChess 0.55 there is a reproducible error with the "takeback" function.

I was playing White against Stockfish (level 0, time 4min+2s, standard opening book). The game went: 1. c4 c6 2. e4 d5. Now I played 3. d4. A few seconds later, while the computer was still thinking, I took back this move. Now Black's clock kept running till 0.00 and the board became unresponsive. The fifth clock button was still functioning, so I rebooted using the "System > Reboot" menu item.

I can reproduce this error every time after playing 1. c4 c6 2. e4 d5 (the computer may need to be forced to play 1... c6 by pressing the middle button ("Alt move").

**Comment by LocutusOfPenguin** [comment]
Hi djdekker,

can y check the log file for python errors?
What version of python-chess y have installed right now?

**Comment by djdekker** [comment]
Hi Jürgen,
There are no Python errors in the log, but there is this message that I don't understand:
    DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
I'm not sure whether this could be related to the takeback error.

The error is 100% reproducible here. I reproduced it many times. In one case I did the fatal takeback and then put the pieces back to starting position. The clock then displayed "ABOR" (without the final letter "T") and then PicoChess became unresponsive.

Perhaps the communication with the board is getting corrupted somehow? Or is the computer sending its messages to quickly one after another? After all, there are lots of messages about the clock being locked, being unlocked, about the score, about the pv and so on.

I'm using python-chess 0.12.3, the version that is mentioned in requirements.txt.

**Comment by djdekker** [comment]
I copied the last part of picochess.log on PasteBin:

http://pastebin.com/rbqKHmb0

In line 316 the illegal move 3... gxf6 has been logged.

**Comment by LocutusOfPenguin** [comment]
that was helpful.
I think, i have an idea what the problem could be [need a dgt-board for check, so takes some time to fix] ;-)
This missing "T" still puzzles me. Let's see.

I'll be back.
Jürgen

**Comment by LocutusOfPenguin** [comment]
Hi djdekker,

on my branch ii fixed the "takeback" issue. Needs more testing (hopefully didnt brake the analysis etc)
Perhaps y can try it out. And for the "T" i dont have an idea. Perhaps solved as a border problem to the first issue.

Won't be online at master branch this week (even fully working > cause of tests).
Jürgen

**Comment by djdekker** [comment]
Hi Jürgen,
Thanks for your effort, which is much appreciated as always. I have updated python-chess and installed v0.56 from your master branch using git, but couldn't get this version running correctly. The clock shows the version number at startup and then seems to freeze, although the board still keeps recognizing user input (like setting a level). I'll try installing again, perhaps I did something wrong here.

**Comment by LocutusOfPenguin** [comment]
Y might take a look at the log (for python errors) , as always ;-)
I'll check tomorrow again myself.

**Comment by djdekker** [comment]
I tried again with a fresh installation of PicoChess 0.56. After starting up and playing 1.f4 (without any changes to level/time/book etc.), the clock is still displaying PICO056 although PicoChess has registered the move. I posted the log file to PasteBin:
http://pastebin.com/v5FnGcK0

**Comment by LocutusOfPenguin** [comment]
i dont get this error. For me working.

. have y updated the python-chess to 0.13?

- Can y try to change these in dgthardware.py (in "stop_clock" function)?

l_hms[0], l_hms[1], l_hms[2], r_hms[0], r_hms[1], r_hms[2],
=>
0, 0, 0, 0, 0, 0,

**Comment by djdekker** [comment]
Yes!! This change in dgthardware.py did the trick. Thank you Jürgen!

Now after 1.c4 c6 2.e4 d5 3.d4 and taking back the last move, the clock display remains locked at "TAKEBACK" (shouldn't it rather display the time?), but it is unlocked after simply playing another move.

**Comment by djdekker** [comment]
Not sure if it is relevant, but it could be: my DGT3000 clock is running on firmware version 2.00, which is rather old. It cannot display lowercase letters, and I can easily imagine that this old firmware might cause some other trouble as well. The people at DGT can update it to the most recent version, so I'll send the clock to them one of these days/weeks.

**Comment by LocutusOfPenguin** [comment]
I found an error and changed the code so the "stop_clock" feature should work now.
But its not tested right now (no board).

For your old dgt3000, i hope that is the reason you're missing a "T".

The "takeback issue" is there all the time (in various versions). Clock starts as soon as you move.
The problem here is, how do y know the user is finished with takeback? Well right now, i don't have the time to develop something clever for this.

**Comment by djdekker** [comment]
v0.56 is working fine now!
My favorite DGT3000 display error is this one (from an early PicoChess version, summer 2015):
![Ne47]
(https://dl.dropboxusercontent.com/u/10122745/Ne47.jpg)
