### ISSUE TITLE
Connection feedback

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#150]
While searching for an E-board some feedback on the status would be appreciated. This could be on the webpage, on screen (already done) and on the clock (in case of a dgt pi). It could display messages like "no  E-board", "USB E-board" and "BT E-board". Maybe with some i'm alive and searching feedback like a "|/-\" sequence behind "no E-board".
It should also keep searching until an E-board is found and search again when the connection is lost.

**Comment by LocutusOfPenguin** [comment]
OK, for the dgtpi part it should be almost done.
I have to check my code with(!) a board to be 100% sure.

What do y mean with "on screen"?

**Comment by LocutusOfPenguin** [comment]
to make it working (on USB), y have to make linux always connect with same name to board.

so, in /etc/udev/rules.d i uploaded a "44-dgt.rules" file with following content:
KERNEL=="ttyACM*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="000a", SYMLINK+="dgtboard"

and use "-d /dev/dgtboard" for startup.
Is this a general solution, Lucas?!?

I didnt test my code on a BT-Board.

**Comment by LocutusOfPenguin** [comment]
The system right now sticks with the "-d" parameter. So, i won't change for example from BT to USB.
A more flexible system is needed.
One way of implementation:
Cycle through /dev/ttyACM0, /dev/ttyUSB0 and /dev/rfcomm0 or higher numbers in case the old /dev not removed in time - perhaps by a "ls /dev/ttyACM*" etc.

**Comment by LocutusOfPenguin** [comment]
For a BT connection there is still a problem.
It doesn't display "no e-Board" when the connection is lost.

**Comment by LocutusOfPenguin** [comment]
Board connection(& btw. jack) status are now reported to all Listeners so y can see their status on webpage too.

**Comment by LocutusOfPenguin** [comment]
One problem still needs to be fixed:
During waiting for a valid board-connection, its not possible to turn the pi off.
