### ISSUE TITLE
clock should tell you what to do

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#151]
At the moment for someone using picochess for the first time it's unclear what to do. This could be improved by displaying "set pieces" while waiting for start position. When a start position is detected "New Game" can be displayed for one second followed by "you move" when you play white or the first move when you play black.

**Comment by LocutusOfPenguin** [comment]
When picochess starts up the following should happen (in correct order):
- Do the #150 stuff - Display the result
- Tell the picochess version like "pico 0.xx" for some time
- "setup pieces" as long its not the starting position - if already in starting pos => go directly to 4
- "new game" for some time
- "you move"

**Comment by LocutusOfPenguin** [comment]
In case of a reconnection see #150 it should also display "You move".
Right now display the connection value (usb, bt)
