### ISSUE TITLE
wrong move indication

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#152]
When making a mistake in the computers move some feedback would be help full, Picking up the wrong piece could give an immediate beep and "wrong move" message, placing the right piece in the wrong spot could give a beep after one second. (in case you are still moving the piece).

**Comment by djdekker** [comment]
This issue makes me think of issue #101.

Currently, the computer move remains displayed on the clock until the user executes it on the board. If the user performs a wrong move on the computer's behalf (either the wrong piece or the correct piece to a wrong square), she will notice that her own clock won't start and conclude that something must be wrong. This way it's fine with me...

**Comment by LocutusOfPenguin** [comment]
yes. This is same as #101 - and its not that easy to do it in clever way!
This issue is still very good and now we have more access to the clock thanks to dgt.
So i talked to lucas and we trying to (finally) do it.

**Comment by LocutusOfPenguin** [comment]
This request is too complex. Esp. when i take into account how long noone did anything to close it ;-)

I implemented it now in following way:
picochess will wait 3sec (can be easily changed) for a stable board position. If this position is invalid/unexpected it will display a message "set pieces" (can be easily changed) on clock.
This wait time should be enough for sliding pieces around, or get fallen down pieces back on place.

The old "set pieces" rest in piece. It didnt worked out very well anyway.
