### ISSUE TITLE
more beep options

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#153]
At the moment you can chose between beep always or beep never. I would prefer something in between like only on wrong moves, or on wrong moves and new computer moves. Beeps after making a move or pushing a button are less desirable.

**Comment by LocutusOfPenguin** [comment]
i began to work on this issue by refactoring the code. Found a long-time-there-bug too.

But my plan is a bit different (as said in email already). Right now, you can turn beeps for buttons on/off independently from the rest => The general goal is: all different beep options can be turned on/off separately.

Jürgen

**Comment by LocutusOfPenguin** [comment]
This code fragment explains my idea abit: (unchecked code is already pushed)
```
class BeepLevel(enum.Enum):
    YES = 0x0f  # Always ON
    NO = 0x00  # Always OFF
    CONFIG = 0x01  # Takeback, GameEnd, NewGame and ComputerMove
    BUTTON = 0x02  # All Events coming from button press
    MAP = 0x04  # All Events coming from Queen placing at start pos (line3-6)
    OKAY = 0x08  # All Events from "ok" (confirm) messages incl. "you move"
```

If that's too complex for a user (=bits) contant's can be made.

**Comment by LocutusOfPenguin** [comment]
Sound is now part of the menu system.
Right now, y go directly to a future "beep" submenu (its not implemented this way).
As soon someone dev's the #154 this can be split in more submenus (for example in "voice" & "beep").

I declare this issue as closed.

**Comment by lucasvdp** [comment]
Thanks @LocutusOfPenguin !

maybe we could put just few options in the menu for those of us who don't speak binary. Which option would people use?

  0= no beeps
  4= events
  5= computer move (+events)
13= all moves (computer move + user move + events)
15= always beep

another question is 15 really the preferred default? maybe 4,5 or 13?  I personaly don't like beeps on button pushes.

**Comment by LocutusOfPenguin** [comment]
The menu now has "Always", "Never" and "Some" BeepLevel.
"some" means the value, y give inside at startup by "-beep" or by picochess.ini.
The values you can calculate from my posting from 1.Jan.

For example if y want beeps on Q-placing, and on button-press:
Q-placing : 4 , Button = 1 => 4+1 = 5 for BeepLevel
