### ISSUE TITLE
audio samples instead of a computer voice

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#154]
Using just a few audio samples a the audio quality can be greatly improved.
Audio samples in English, Spanish, France, German, Italian and Dutch can be easily arranged.

What format is best suited?
Which samples do we need? A-H+1-8+ pieces+"check"+"mate"
maybe some extra's like name of the language (for playing after selection), wrong move, new game,

**Comment by LocutusOfPenguin** [comment]
Here are some sounds missing....This list is prob. still not complete:
RESULT_TIME_CONTROL
RESULT_ABORT
RESULT_FIVEFOLD_REPETITION
RESULT_SEVENTYFIVE_MOVES
RESULT_INSUFFICIENT_MATERIAL
PICOCHESS (would be nice to promote himself , ha)
60-90 (or not 30,40,50)

All from the menu like "Fischer, Time, Blitz, Level, ...."

**Comment by LocutusOfPenguin** [comment]
v0.78 is the first (released) version trying to solve this issue.
Needs more (complete) voice sets.

**Comment by LocutusOfPenguin** [comment]
closed by v0.80
I only would need christina's "user white" & "user black" speakings.
In meantime, i copped the "white" & "black" from her.
