### ISSUE TITLE
Is j-performance.bin book too long of a name? 

### ISSUE THREAD

**Issue by mixographer** [jromang/picochess#156]
I get this error that hangs my pico if I accidentally select performance.bin:

2015-12-16 22:10:56.952 WARNING dgthardware - _display_on_dgt_3000: DGT 3000 clock message too long [performance]

**Comment by LocutusOfPenguin** [comment]
this warning only means that the text is too long and its therefore cutted. In general its a sign for a developer that his string is not suitable - no problem for a user.

That shouldn't result in a "hang of program". So this itself isn't the cause of yr problem.
Perhaps y can post more from yr log file (esp what happens after this warning).
What picochess version y are using?

**Comment by mixographer** [comment]
I pulled the latest from 'stable' yesterday. I'm on a usb board with dgt3000 clock.
