### ISSUE TITLE
No module named 'chess'

### ISSUE THREAD

**Issue by mixographer** [jromang/picochess#157]
Should this say "No module named 'python-chess?'

**Comment by LocutusOfPenguin** [comment]
sorry? what y mean?

**Comment by djdekker** [comment]
The error message is correct as it is.

Although the 'chess' package can be found in a GitHub repository called '[python-chess](https://github.com/niklasf/python-chess)', it is known on your computer as 'chess'. See the directory `/usr/local/lib/python3.4/site-packages/chess`.
