### ISSUE TITLE
Highlight last move on web GUI

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#163]
I was testing the new REMOTE PLAY feature (BTW, somebody should update documentation on this) and it works surprisingly well! Bravo!!! If appropriate port on home router is opened and forwarded, it's only a matter of sending a friendly remote player (or tutor) the URL of your picobot, off we go.

The only immediate problem I notice is the lack of last move indicator. When playing angainst remote opponent we both stumbled upon the problem of "whose move is it?". At this time the board display offers no hint of what was the last move. Highlight of last move (a la lichess.org) is highly necessary.

Also, some sound when the move is made would be probably welcome.

**Comment by ifekali** [comment]
Oh, by the way, when in remote play mode, it would probably be wise to disable the engine evaluation and hint in GUI. Too easy to cheat :)

**Comment by LocutusOfPenguin** [comment]
Hi Jonas,
have y taken a look at the new webserver interface >=0.73?

And if y use >=0.73 can y comment on if remote still working for you?
I don't have hardware ready to test that myself.

Perhaps you can shortly describe how to set up remote in detail.
Although i just updated the docu, the remote part is still missing.

**Comment by LocutusOfPenguin** [comment]
No response (since months) to my Q => (auto)close
