### ISSUE TITLE
v0.60 log file problem

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#167]
PicoChess v0.60 does not start.

It is trying to place picochess.log into a folder /opt/picochess/log/opt/picochess, which does not exist.

After manually creating the /opt/picochess/log/opt/picochess folder, PicoChess starts fine.

**Comment by LocutusOfPenguin** [comment]
the -lf flag must be the filename only.
Its automatically put inside the logs folder.
This is all done due to the "rotating log file" issue.

In general some INI flags have been changed in v0.60
