### ISSUE TITLE
PicoChess gets stuck when engine runs out of time

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#170]
When the engine (I tested with Stockfish 7) runs out of time, the clock displays 'TIME' and the game does not continue => PicoChess is stuck! The clock keeps displaying 'TIME' even when the pieces are put back in starting position. No response anymore :(

It is easy to let an engine run out of time. Start a 1 minute blitz game and switch sides when you've got only a few seconds left.

**Comment by LocutusOfPenguin** [comment]
Hi DJ,
cant reproduce that. After "time" (engine's side) my system is still working.

**Comment by djdekker** [comment]
Tested again with Stockfish => no problem. Closing this issue.
