### ISSUE TITLE
Wrong time indication with Fischer tempo

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#178]
Timer issue in PicoChess v.063:

When the user selects a Fischer tempo, the bonus time for the first move is already added to the time **before** the first move is made. So at the start of the game the clock displays, for example, "3.02 3.02". This is wrong. The time bonus should be added **after** each move. So at the start of the game the clock should rather display "3.00 3.00" instead of "3.02 3.02".

**Comment by LocutusOfPenguin** [comment]
but dgt said, it must be this way concerning fide...also if y take a look at their fischer modes, its so.
I changed it on their behalf extra this way, ha.

**Comment by djdekker** [comment]
I see! No problem, it just feels so counterintuitive...

The folks at DGT are right. On page 21 of the FIDE Arbiter's Manual 2014 the rules about the increment for the first move are very clear.
