### ISSUE TITLE
Buttons in normal game mode

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#182]
Update: changed back button functionality to include last user move. 

while in normal game mode you can use the 5 buttons for some specific functions. Maybe they can be swapped around a bit to get a more logical approach and to include a play/pause function. To explain I will give a function for each button in each mode you can encounter during a game.

button | your turn | engine running | engine finished (move is displayed)
--- | --- | --- | ---
< back | last computer move | last user move | last user move
- minus | your current score | your current score | your current score
>II play/pause | pause/resume | move now (display move and pause, resumed on making the move) | calculate & display alternate engine move
+ plus | display hint for your move | display sneak peak of engines current best move | display engines best move (ponder move)
> forward | enter menu | enter menu | enter menu
lever change | switch sides (engine started) | switch sides (engine stopped, you can do any move yourself) | switch sides (the displayed move is canceled and you can do any move yourself)

This way all buttons do roughly the same in all states.
* < back = last computer move
* - minus = your (maybe negative) score
* play/pause = play/pause
* + plus = display a good move
* > forward = menu
* lever change = change sides

This means that you can play engine against engine or human against human by changing the lever after every move which sounds like a nice feature. You can also pause the game at any point and you can get a hint of what the engine is thinking off.

What do you guys think?

p.s. thanks to @BenDGT en @LocutusOfPenguin for their collaboration on this topic.

**Comment by djdekker** [comment]
I like the consistency of the button functions and the new function of the lever! When the user switches sides, could the little white and black kings on the clock also switch?

**Comment by lucasvdp** [comment]
while the clock is being displayed the king icons depend on the lever position at first start of the clock. Unfortunately we can not change this by software. The easy fix is to have the white side lever up at startup and the icons would be displayed correctly during the whole game.

**Comment by LocutusOfPenguin** [comment]
I think, when "< back" & "engine running" should display the "last USER move".

Your table describes the "normal" mode. For example in analysis mode "stop thinking" doesn't make sense. The buttons are changed to reflect such situations. For your info.

"display alternate engine move" is not "display" by itself => its more "re-calculate the position & then display new move" ;-)

**Comment by lucasvdp** [comment]
Then I guess also engine finished should display the last user move. This way you know what to take back to undo your move. And in principle you can "takeback" the whole game. (long move notation needed?)

Are there any extra options we want in the other modes? If not we can just use the same button assignments and leave away the functions that can't be used in these modes.

**Comment by LocutusOfPenguin** [comment]
That's a very good idea (with takeback) to display the (new) last move.
Enables the user to revert the whole game step by step.

This takeback case isn't handled in any version until now but its an improvement so i will code this in.

**Comment by LocutusOfPenguin** [comment]
i updated the "engine finished (move is displayed)" part
around ">II play/pause" & "+ plus" part to reflect the new situation.

Also i will implement "display moves aligned on the players clock side" as a bonus :-)

**Comment by BenDGT** [comment]
Hi Jürgen,

That’s great. Issue 182 is number 18 on the Beta list that Lucas sent on Wednesday, see attachment. What parts of issue 182 still need to be done?
And the alignment on the display (my idea, should look nice) was on the wish list as item 7.

We are getting close to the release of the product. Next to the software I am about to finish the last details on mechanical optimizations, artwork, packaging, manuals, accessories, pricing etcetera. The story is getting around in the market and the reactions are always very positive. The product really improved the last 6 months!

Looking at the Beta list I expect Lucas to work on items 9, 13, 14, 16 and 19. That is if he returns from the desert.
Issue 15 is about the engine Maverick. My proposal is to delete that engine.

By the way, where do the sf-hmn, sf-beg and sf-dd engines come from? I guess they are variations on Stockfish? And what do you know about dsaros and claud2?

That leaves item 3, 4, 7, 17 and 18.
Jürgen and Benjamin: any idea how big the effort is for finishing those, and what items would you like to do yourself?

Keep up the good work,
thanks,
Ben Spenkelink
Manager Product Development
email: ben@dgt.nl
Digital Game Technology, www.DigitalGameTechnology.com, telephone +31 (0) 53 4305195 or +31(0)6 36139466
address: DGT B.V. , Hengelosestraat 66, 7514 AJ Enschede, The Netherlands
[cid:image001.png@01D1B27A.31FFD8A0]

**Comment by LocutusOfPenguin** [comment]
@BenDGT
Since my eMail to y => i think, this issue is now tweaked as said (surely needs testing) but i'm confident, its solved for release very soon.

One advantage not mentioned over the whole discussion here:
The lever system allows Revelation II users to switch sides now!

**Comment by LocutusOfPenguin** [comment]
@lucasvdp 
Its done. When y return from the desert please close this issue.
