### ISSUE TITLE
Increment not added correctly

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#184]
The computer does not receive the time increment that it deserves in these conditions:
* Stockfish engine (default)
* level 3
* time control 1m + 1s
* opening book 'Open'
* player answers each computer move immediately

In these conditions, when playing a line from the opening book, the engine does not receive the correct increment. For instance, after 1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Bc5 5. Be3 Qf6 6. c3 Nge7 7. Bc4 Ne5 8. Be2 Qg6 9. O-O d6 the computer's clock (Black) showed 1.03, although the computer was playing an opening line that should have cost no thinking time.

**Comment by LocutusOfPenguin** [comment]
fixed with v0.68
