### ISSUE TITLE
Webserver should forget position

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#186]
After playing a game and putting the pieces back into starting position, the web server correctly displays the starting position. But... now press 'Sync' and the final position of the finished game reappears! If 'Sync' really means "synchronize with the board", then the web server should have forgotten about the previous game. Is the last FEN perhaps kept in some cache?

**Comment by sshivaji** [comment]
Yes, it is.

The problem is that the setup of the start position does not really
register as the "last_fen". This is easy to fix.
