### ISSUE TITLE
Force Quit Engine Not Working?

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#188]
PicoChess contains code to force quit misbehaving engines. In the case of Cheese 1.8 this code is called, but it seems that it doesn't work. I've got the Cheese 1.8 ARM binary installed as /opt/picochess/engines/armv7l/d-cheese.

The following happens when starting PicoChess with -e ./engines/armv7l/d-cheese and then switching to another engine using the clock menu:

```
Traceback (most recent call last):
  File "picochess.py", line 841, in <module>
    main()
  File "picochess.py", line 575, in main
    if engine.terminate():  # If you won't go nicely.... 
  File "/opt/picochess/engine.py", line 217, in terminate
    return self.engine.terminate()
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 1323, in terminate
    self.process.terminate()
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 398, in terminate
    self.process.terminate()
  File "/usr/lib/python3.4/subprocess.py", line 1686, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

Is this due to PicoChess or to an error in the Cheese engine?

**Comment by LocutusOfPenguin** [comment]
where to find this cheese?
i want to compile it myself...or even forget this engine (since there are many out-of-box working alternatives!)

**Comment by djdekker** [comment]
http://cheesechess.free.fr/

**Comment by LocutusOfPenguin** [comment]
ok, downloaded it (but still no source code :-1: ).
Engine doesnt want to be stopped.
Well, this can be a python-chess problem but i think a "cheese problem".
Cant do something for that. For me, this is "closed".

**Comment by djdekker** [comment]
Ok, I get it. Cheese seems to want to play forever haha! I agree with you, let's close this issue.
