### ISSUE TITLE
SMTP password not hidden in log

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#191]
In the line "DEBUG  picochess - main: startup parameters" of the log file header, the SMTP password is not being replaced by '*****'. Is there a problem with the dash in smtp-pass in picochess.py?

**Comment by djdekker** [comment]
Thanks Jürgen, this solves the header.

The log file still shows the mail password **after** the game because of line 124 of pgn.py.

**Comment by LocutusOfPenguin** [comment]
i see. Since its there all the time, i gonna commit this missing "#" next week together with the new version :-D
