### ISSUE TITLE
EMail Settings not correct

### ISSUE THREAD

**Issue by bornhaeusser** [jromang/picochess#192]
From Email Adress should be variable and not always no-reply@picochess.org

Also the To: is missing in the SMTP Settings in pgn.py

Each received EMail is the to is empty.

**Comment by LocutusOfPenguin** [comment]
The newest upcoming version (v0.68) will get a "To" header.
What is the reason why y want to have a different sender eMail adr?

**Comment by bornhaeusser** [comment]
Many Spam Filters see that the Email arrives from picochess.org comes from a diffrent IP Adress....

Example: Picochess send from my SMTP Mailserver IP 123.123.123.123

Mailserver looks: Ahh a mail from picochess.org -> show me ip fom them = 321.321.321.321

Thats not the IP where the EMail comes from -> so it could be spam

**Comment by LocutusOfPenguin** [comment]
fixed with v0.68
