### ISSUE TITLE
Webserver notation stops at castling [Chess960 Mode]

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#197]
When playing a game of Chess960, the webserver notation stops when the player castles, but the diagram display continues correctly for the remainder of the game.

Example:
**Starting position**: 343 (NRBKQRNB)
**Moves**: 1. f4 d6 2. b3 g6 3. c3 Nf6 4. Bb2 c5 **5. 0-0-0** Qb5 etc. => the webserver keeps displaying the DIAGRAM correctly, but does not show the game NOTATION anymore after 4... c5. Is it having some difficulties with 5. Kd1xb1?

**Comment by LocutusOfPenguin** [comment]
I will take a look to fix this in the v0.72 version (my current PLAN).
This will address some Webserver issues (like #193)
In meantime decide for the "bug" flag :-)

**Comment by LocutusOfPenguin** [comment]
It seems to come from the lib "chess.js" which cant handle chess960 modes.

**Comment by LocutusOfPenguin** [comment]
StartPos:
nrbkqrnb/pppppppp/8/8/8/8/PPPPPPPP/NRBKQRNB w KQkq – 0 1

EndPos (before 0-0-0):
nrbkqr1b/pp2pp1p/3p1np1/2p5/5P2/1PP5/PB1PP1PP/NR1KQRNB w KQkq – 0 1

**Comment by LocutusOfPenguin** [comment]
Ok, i began to fix this myself since on the chess.js issue https://github.com/jhlywa/chess.js/issues/122 is no progress for months.

**Comment by LocutusOfPenguin** [comment]
Hi DirkJan,
should be fixed now => online with new v0.9x version.

**Comment by djdekker** [comment]
Thank you Jürgen! I cloned the cg branch of your repo and tested how the web server handles castling in Chess960 games. It works like a charm!!
