### ISSUE TITLE
Init script - "screen -dm US pc " missing in line 31

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#198]
On my odroid XU4 I often use the startup script "picochess.init" put in /etc/init.d and let picochess run in the background :)

A. In Version (V71, maybe earlier) the startup of picochess in line 31 does not contain a prefix (screen -dmUS pc ) any more. Also I would like you to add a change of the  path to the picochess files before calling the picochess:
1. cd /opt/picochess
2. screen -dm US pc pyton3 picochess.py -d $dgt_port -web -------

B. with the new versions do we need -d option?

C. Since I always use the Odroid with a Display Monitor I have added some simple code lines to give an info about  the DGT Board and connection state before startup. I will give you these lines in second posting.

Kind regards Laterunner
Kind regards

**Comment by LocutusOfPenguin** [comment]
Hi Laterunner,

I dont have such hardware, so i cant help.
This line was removed from @sshivaji . Maybe he can help y.
Same for other issue #200.

On Jessie, y don't need these script folder anymore ... that includes the "-d" cause picochess is now able to find the dgt board itself.

Maybe, y can upgrade yr system to a XU4 -Jessie system?!?
Jürgen

**Comment by sshivaji** [comment]
Ok, not sure why I removed those lines, probably just drunk or more likely just an accidental copy from old code. Fine to do as requested :)

**Comment by Laterunner** [comment]
Hi shiv, thank you for reply
I still use this little init script line to start (and stop with kill) picochess. For linux newbies an interesting way to execute a program. 
- never stop learning -
By the way picochess 0.77 (manual install) no problems on odroid xu4 hardware!

Always Enjoy your wine ;)

Kind regards
Laterunner

**Comment by sshivaji** [comment]
The screen command was first introduced by Jean-Francois Romang to
Picochess. Its quite a useful command. I did twiddle with the options a
bit. I think we may not need to use screen, but its a simple way to debug
the program. The -d specifically runs this in daemon mode, however we dont
need it as picochess.py itself is running in daemon mode.

Glad to hear it still works on odroid xu4!
