### ISSUE TITLE
Levels in Texel not supported

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#207]
Texel 1.06 has levels, but these are not working in PicoChess.

Unlike other engines Texel has a "Strength" parameter instead of "UCI_LimitStrength". There is no "UCI_Elo" parameter.

The "Strength" parameter can take any value from 0 (weakest) to 1000 (strongest).

**Comment by LocutusOfPenguin** [comment]
Kick it :-)
You need to create a texel.uci file similar to the others FOR THE MOMENT.
like so:
`
[Name]
Strength = X
`

**Comment by djdekker** [comment]
No need to dive into this issue any further... it works nicely with the b-texel.uci commit.

I think this issue can be closed.
