### ISSUE TITLE
Insert ECO tag in pgn file

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#217]
This one was suggested sometime on the PicoChess forum: would it be useful if PicoChess stored the ECO code in a tag in the .pgn file header?

A complete list of ECO codes and moves is already freely available at the GitHub repository of the Arasan engine:
[https://github.com/jdart1/arasan-chess/blob/master/book/eco](https://github.com/jdart1/arasan-chess/blob/master/book/eco)

It should be possible to compare the first X moves of the game with this list, find the appropriate ECO code and write it to an ECO header, shouldn't it?

**Comment by LocutusOfPenguin** [comment]
I think, y need to go backwards in the game, and compare positions (not moves) cause of transitions.
Your way is simpler and most of time working too...but cant get all codes.
Surely, thats possible to develop...but not in this moment (if im speaking for MYSELF only).
