### ISSUE TITLE
Update 0.78

### ISSUE THREAD

**Issue by bornhaeusser** [jromang/picochess#219]
After the Update i got:

Nov  3 13:01:23 raspberrypi python3[397]: Traceback (most recent call last):
Nov  3 13:01:23 raspberrypi python3[397]: File "/opt/picochess/picochess.py", line 49, in <module>
Nov  3 13:01:23 raspberrypi python3[397]: from talker.picotalker import PicoTalkerDisplay
Nov  3 13:01:23 raspberrypi python3[397]: File "/opt/picochess/talker/picotalker.py", line 31, in <module>
Nov  3 13:01:23 raspberrypi python3[397]: import sounddevice as sd
Nov  3 13:01:23 raspberrypi python3[397]: ImportError: No module named 'sounddevice'
Nov  3 13:01:23 raspberrypi systemd[1]: picochess.service: main process exited, code=exited, status=1/FAILURE
Nov  3 13:01:24 raspberrypi systemd[1]: picochess.service: control process exited, code=exited status=1
Nov  3 13:01:24 raspberrypi systemd[1]: Unit picochess.service entered failed state.

**Comment by LocutusOfPenguin** [comment]
how did y update?
if y let picochess autoupdate, it should run "pip3" which installs the "sounddevice" , and more. Then there is a problem.
If y did it by hand, y must run "pip3" yourself. See docu & relase notes.

**Comment by bornhaeusser** [comment]
did do nothing. autoupdate did run.
trying to pip3 manually:

  Rolling back uninstall of cffi
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8ewutu4/CFFI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lw84obmx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_8ewutu4/CFFI/

**Comment by LocutusOfPenguin** [comment]
sudo apt-get install python3-numpy
sudo apt-get install libportaudio2
sudo apt-get install python3-cffi

does that work without problems?
Afterwards y can try pip3 by hand one by one..and report each problem.
sudo pip3 install sounddevice
sudo pip3 install pysoundfile

**Comment by bornhaeusser** [comment]
Seems to be without misstakes:

pi@raspberrypi:~ $ sudo apt-get install python3-numpy
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-numpy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt-get install libportaudio2
Reading package lists... Done
Building dependency tree
Reading state information... Done
libportaudio2 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt-get install python3-cffi
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-cffi is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo pip3 install sounddevice
Collecting sounddevice
  Using cached sounddevice-0.3.5-py2.py3-none-any.whl
Requirement already satisfied: CFFI in /usr/lib/python3/dist-packages (from sounddevice)
Requirement already satisfied: pycparser in /usr/local/lib/python3.4/dist-packages (from CFFI->sounddevice)
Installing collected packages: sounddevice
Successfully installed sounddevice-0.3.5
pi@raspberrypi:~ $ sudo pip3 install pysoundfile
Collecting pysoundfile
  Downloading PySoundFile-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: cffi>=0.6 in /usr/lib/python3/dist-packages (from pysoundfile)
Requirement already satisfied: pycparser in /usr/local/lib/python3.4/dist-packages (from cffi>=0.6->pysoundfile)
Installing collected packages: pysoundfile
Successfully installed pysoundfile-0.8.1
pi@raspberrypi:~ $ sudo reboot



Still no success:

Nov  3 14:09:02 raspberrypi python3[397]: import sounddevice as sd
Nov  3 14:09:02 raspberrypi python3[397]: File "/usr/local/lib/python3.4/dist-packages/sounddevice.py", line 313, in <module>
Nov  3 14:09:02 raspberrypi python3[397]: """)
Nov  3 14:09:02 raspberrypi python3[397]: File "/usr/lib/python3/dist-packages/cffi/api.py", line 103, in cdef
Nov  3 14:09:02 raspberrypi python3[397]: self._parser.parse(csource, override=override, packed=packed)
Nov  3 14:09:02 raspberrypi python3[397]: File "/usr/lib/python3/dist-packages/cffi/cparser.py", line 166, in parse
Nov  3 14:09:02 raspberrypi python3[397]: self._internal_parse(csource)
Nov  3 14:09:02 raspberrypi python3[397]: File "/usr/lib/python3/dist-packages/cffi/cparser.py", line 174, in _internal_parse
Nov  3 14:09:02 raspberrypi python3[397]: self._process_macros(macros)
Nov  3 14:09:02 raspberrypi python3[397]: File "/usr/lib/python3/dist-packages/cffi/cparser.py", line 236, in _process_macros
Nov  3 14:09:02 raspberrypi python3[397]: '%s 0x1FF" for now' % (key, key))
Nov  3 14:09:02 raspberrypi python3[397]: cffi.api.CDefError: only supports the syntax "#define paNoDevice ..." (literally) or "#define paNoDevice 0x1FF" for now
Nov  3 14:09:02 raspberrypi systemd[1]: picochess.service: main process exited, code=exited, status=1/FAILURE
Nov  3 14:09:02 raspberrypi systemd[1]: picochess.service: control process exited, code=exited status=1
Nov  3 14:09:02 raspberrypi systemd[1]: Unit picochess.service entered failed state.

**Comment by Laterunner** [comment]
H Jürgen
Same and more issues on Ubuntu 14.4.5  (Odroid XU4) I lost my working V0.77 installation!
- maybe it is better to revert to Picochess 0.77 and make a new branch Master2 on github?
Is it possible to reinstall V 0.77?

**Comment by LocutusOfPenguin** [comment]
Sorry to hear.
if y can live without "voice" for the moment, y can update again, and not use the voice parameters.

If y want to go back to v0.77, y can type "sudo git checkout v0.77". Disable auto update then.
Revert to "uptodate" with "sudo git checkout master"

**Comment by Laterunner** [comment]
Hi Jürgen, 
ok I reverted Back to V0.77
(by sudo git checkout v0.77)
Now however my DGT 3000 says Pico 0.76 (!) - definitely before I already had a 0.77 Version :(..

at least this Version works with speech and and web.

The 0.78 Version does not yet work for me. I am curious what is wrong.
My System Ubuntu LTS 14.4.5, so far up to date.
I did get numpy, libportaudio2 and python3 -cffi as you described.
Picochess 0.78 will now load (although I get a DGT 3000 message 0.78)
would you need more information?
Kind regards
Laterunner

**Comment by LocutusOfPenguin** [comment]
@Laterunner 
Ok, this tag "v0.77" is one commit too early. So, y see 0.76 instead of 0.77. But the only difference between them is this name. So, the function itself is 100% same.
Tags => short names for the sha (git) codes.

See here:
https://github.com/jromang/picochess/commit/7f246d61b4524a9ddc8f3a06c2f939fede4565c5

**Comment by LocutusOfPenguin** [comment]
@bornhaeusser 
Since y said (on forum) y successfully updated, can this issue be closed?

For reference i post how to setup a sdcard for picochess using the new jessie (with pixel inside) from beginning:
login & sudo su
update&upgrade the system
cloned picochess

apt-get install libssl-dev
apt-get install libffi-dev

took the new requirement.txt file (with 2 extra lines) to be sure the cffi is in newest version
pip3 install --upgrade -r requirements.txt

Should run without errors, and then picochess is ready to talk (dont forget to change your picochess.ini file with the new voice names)


@Laterunner 
What about yr XU4 system? Can y try it again? Sadly, y more or less alone cause i dont have this system.
Jürgen

**Comment by mgeier** [comment]
Looks like the version of CFFI is too old, see https://github.com/spatialaudio/python-sounddevice/issues/49
Which version were you using?

**Comment by LocutusOfPenguin** [comment]
i guess all is done (no answer) => close.
Also we have a new version ;-)
