### ISSUE TITLE
Escape character used in pgn file

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#220]
In the pgn file PicoChess writes the engine level between a slash and a backslash, like this:

White="Stockfish 7 /Level 6\"

When importing the pgn file in, e.g., Hiarcs Chess Explorer the backslash is treated as an escape character.

So I'd like to suggest to write the level in another way, for example in parentheses like this:

White="Stockfish (Level 6)"

**Comment by LocutusOfPenguin** [comment]
Hi DJ,
how about [ ] , cause i dont want so much ( ) inside.

**Comment by djdekker** [comment]
Hi Jürgen,

No problem, of course.

I'm not even sure whether this isn't a bug in Hiarcs rather than in PicoChess.
