### ISSUE TITLE
After update to 0.82, nothing works

### ISSUE THREAD

**Issue by karljs** [jromang/picochess#226]
I flashed the v0.79 image and set both `enable-update = True` and `enable-update-reboot = True` in my `picochess.ini` file.  After I forced a reboot, it seems to have performed the update to v0.82.

Unfortunately, this has completely borked my setup and while the board establishes a bluetooth connection (indicated by a solid green light) the clock never shows any message and I can't access the engine or any of the settings.

I replicated this by going through those steps again (re-flashing and re-updating) and it leads to the exact same results -- 0.79 works but 0.82 does not.  I've attached the log file which seems to suggest that things are working but the interface to my clock isn't working.  Any suggestions?

[picochess.log.txt](https://github.com/jromang/picochess/files/751730/picochess.log.txt)

**Comment by LocutusOfPenguin** [comment]
Hi,
your clock doesnt answer the "are y there, clock?" request.
=> so, messages to the clock are always ignored. Strange.

Does it work on older versions? And what clock y have? Are y sure, the clock is connected correctly (+has enough battery, etc)?

If it works on older version maybe叔叔 不约 第530章  y can help me, to try to find out where it brakes. Are y able to use some "git checkout <sha-code>" with a moved away ini file (cause the file syntax is changed)?

Jürgen

**Comment by ScallyBag** [comment]
Jürgen,

Could this be the -web to -w in "/etc/systemd/system/picochess.service" ?

If so, maybe we should include this in the release notes.

Cheers,

Al.

**Comment by LocutusOfPenguin** [comment]
no, Al
its ONLY the clock (from log file).
Actually, picochess is working (so the title is abit wrong, ha).

**Comment by karljs** [comment]
@LocutusOfPenguin I am using the DGT 3000 and it has relatively new batteries.  Everything works great with version 0.79.  I'm happy to check out a particular version of the code and test it if you let me know which hash to try.

**Comment by LocutusOfPenguin** [comment]
hmm, thats same HW as i normally use (for developing).

Perhaps y can narrow the area where the problem first come up. If y first(!) try
git checkout v0.80 then v0.81 ...i dont need to take a look at too much commits..Surely, thats not enough, but this way, i can at least narrow the 136 commits abit :-)
I generally trying to half the rest-commits (if i have no idea), to reduce the tries, ha.

If y not at top, perhaps move the picochess.ini file away, cause it might cause problems, and for this clock tests, y dont need yr prefered settings.

**Comment by karljs** [comment]
@LocutusOfPenguin Well, this is a bit embarrassing to admit, but I think the problem is with my clock cable.  I was getting unpredictable behavior as I tried different versions and after jiggling the cable  every version (including the most recent) started working just fine.  Sorry to waste your time.

Just for my own purposes, can I just get back to normal behavior by checking out the master branch?  Or should I check out specifically v0.82?  Thanks for any advice.

**Comment by LocutusOfPenguin** [comment]
No Problem. I'm happy it is working for you now!
Ive learned to not only ask for the battery (which was the problem lately for many issues), instead also for a cable break.

You should checkout "master" to be on top. These v0.xx are tags for sha's which for v0.82 dont need to be the absolute top of development.

Can this issue be closed now, or want to take further look?

Jürgen

**Comment by karljs** [comment]
Thanks for the tips.  I'm closing the issue since it wasn't a real one to begin with.
