### ISSUE TITLE
Bug in setting up position

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#229]
There is a reproducible bug when setting up a position:
1. clear the board and set up this position: White Kg6 Re7, Black Kg8.
2. start DGTPi (running PicoChess v0.83), it shows "set pieces".
3. using the clock, select "Position" => the clocks shows "side move B" (BTW why not "side move W"?).
4. select "side move W".
5. select "W B", "uci960 no" and "scan board".
6. press the clock lever => the clock says "player B" and "1.Rd1#".

It seems that PicoChess is getting the board orientation wrong.

**Comment by LocutusOfPenguin** [comment]
Hi DJ,
checked on console mode (no board right now).
Seems to only happening with PI (on XL/3000 i didnt get this)
