### ISSUE TITLE
Evaluation not always in two decimals

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#232]
The web server does not always show the evaluation of the position in two decimals. The picture below shows that the evaluation of the analyzing engine is being displayed as "0" rather than "0.00". I think it would be more consistent always to use two decimals, just like the display on the clock.

![engine_evaluation](https://cloud.githubusercontent.com/assets/5346286/24827621/8f43acec-1c4d-11e7-84fc-644ac6ec60e8.png)

**Comment by LocutusOfPenguin** [comment]
i could only image it was a "lowerbound" or "upperbound" result.
For this, i put a "<" , ">" infront of score now.

Im not sure, this "webserver engine" stuff will survive 2017, even its fixed now.
