### ISSUE TITLE
Wrong color in ponder mode

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#233]
When the board is set up in starting position with colors reversed (White pieces on rows 7+8, Black pieces on rows 1+2), the DGTPi clock and the web server display White moves like Black (1... e4) and Black moves as White (1.e5).

**Comment by LocutusOfPenguin** [comment]
The display is NOT showing 1.e5 for a BLACK move, instead it shows the side (for black) is on left side of clock.
Picochess expects the clock on the board cable side - which is another problem if y have a DgtPi & BT Board or if y look at the webserver display (which is a copy of the clock display)
In this regard the current stage is fully correct. But i agree its confusing (esp, cause there is a move number displayed - without it, y can better image the result wanted)!

Perhaps need to give up the side switching for move display, and stay with "  1.     e5" or "1.     e4"

**Comment by djdekker** [comment]
Sorry for creating confusion here! I didn't remember the logic behind the clock display. :( Thank you for getting this clear again.

What remains, however, is the web server display. Here is the **correct** display of the computer's move 1...e5 when the game starts with the pieces in normal position:
![normal](https://cloud.githubusercontent.com/assets/5346286/25399507/f6a9acf6-29ef-11e7-9d76-76f8037d7372.jpg)

And here is the **incorrect** display of the computer's move 1...e5 when the game starts with colors reversed. Black's move 1...e5 is displayed without the three dots, so it looks like it's a White move:
![reversed](https://cloud.githubusercontent.com/assets/5346286/25399520/fbce9908-29ef-11e7-98b7-986d84b64f68.jpg)

**Comment by LocutusOfPenguin** [comment]
Please remember that the webserver display is a copy of the dgt clock. These "..." only means "right aligned".
so a "1.e5" means on the CLOCK: "1.e5_________" which shows that e5 is the down side (on yr last pict the white pieces"), so , its correct. The clock is supposed to be near the Ra1.
If y reverse the board, the ws board display is not AUTO-flipped.

As said, im thinking to REMOVE this clock-side-switching based on the dgt board orig status.
So, a white move is left aligned and a black move is right aligned.
This will remove this confusion, but on the other side, this sided-display is also not bad. But i cant follow two gods.

**Comment by LocutusOfPenguin** [comment]
I'll try it another way:
This "clock-side-switching" let the move be displayed on the origin of the pieces.
Thats same with writing, if y not reverse the board, but the clock display is NOT a writing display => it displays a white move, where the white pawns been, and similar for black.

Also for the webserver clock y must image, its 90 degrees anti-clock turned.
If y reverse the board, y must also "flip" the ws board to see the same as on a real board/clock.

**Comment by djdekker** [comment]
> Please remember that the webserver display is a copy of the dgt clock. These "..." only means "right aligned".
so a "1.e5" means on the CLOCK: "1.e5_________" which shows that e5 is the down side (on yr last pict the white pieces"), so , its correct.

Thank you for explaining Jürgen! I understand what the "…" in the webserver display mean. My point is that it's exactly the direct link between clock display and webserver display that's causing trouble here. The use of "…" meaning "right aligned" is not in accordance with the standard way of writing Black moves. The standard has been defined in §8.2.2.2 of the PGN specification:

> A white move number indication is formed from the integer giving the fullmove number with a single period character appended. A black move number indication is formed from the integer giving the fullmove number with three period characters appended.

At home I have my DGTPi standing behind the Bluetooth board rather than on the left side, and I like the alternating left/right display of the moves very much! 😃 On the clock the logic appears to be: **human** moves left, **computer** moves right. Would it be difficult to change this into: **White** moves left (1.e4_________), **Black** moves right (1._________e5)?

**Comment by LocutusOfPenguin** [comment]
As i said, this is NOT a display concerning this §8.2.2.2 It never been! 
It shows the moves on the side the pieces been at start.
Its by "accident" same if y not reserve the board - thats all.
So, the logic is not "white left", instead "white left", is standard startup, "right left" if reversed board.

All this was made without a PI in mind => the clock cable is short => the clock can only be on left side of board and without a webserver clock display plus no move number displayed.
Nowadays these preconditions are no longer valid for every person (you just gave an example).

I explain it so in detail, cause even i change it now, the old picochess versions stay as they are. Esp on the sold PIs (with v0.75). I hope y understand its not a bug...its so by design...and now abit confusing.

Anyway, changing this to "game turn" is not hard at all, actually, it makes the code even easier, and i will change this now.

**Comment by djdekker** [comment]
Thank you for your patience Jürgen. :smiley: I understand!
