### ISSUE TITLE
Accelerate speech ?

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#234]
Speech output is a nice feature in picochess. Sometimes I would prefer speech being a little bit faster (1,5 - 2 times). Is there an easy way to accelerate speech in picochess? Maybe a factor in picochess.ini?

Kind regards laterunner

**Comment by LocutusOfPenguin** [comment]
picochess using "ogg123" internally. There are these flags, which maybe is what y looking for:

-x n, --nth
    Play every 'n'th decoded block. Has the effect of playing audio at 'n' times faster than normal speed. 
-y n, --ntimes
    Repeat every played block 'n' times. Has the effect of playing audio 'n' times slower than normal speed. May be with -x for interesting fractional speeds. 

But i didnt test it out (so, i dont know, how the speech sounds like).

**Comment by Laterunner** [comment]
ok  -  could x and y values entered via picochess.ini? that would be a nice Feature!
Kind regards
Laterunner

**Comment by LocutusOfPenguin** [comment]
yes, thats easy...but first need to see if the voices are OK, if i manipulate them this way.
And it has to work (acceptable) on all languages.

**Comment by Laterunner** [comment]
Waooo I hope x,y values to accelerate speech will be a feature soon. Chess needs fast transmisson of moves and fast thinking :)

Kind regards Laterunner

**Comment by LocutusOfPenguin** [comment]
see my last sentence...and i dont have time right now to test this out.

Since it isnt a big development i will be THEN (after voice tests) online very soon.
But i prefer to have ONE value (=voice factor), not x/y and probl. a set of values like "0,5 | 1 | 1,5 | 2" something ... not everything a user can image of. All depends on "how it sounds".

But hey, there is no guarantee on release date.

**Comment by LocutusOfPenguin** [comment]
tested abit with X/Y values => that DOESNT work :-(

leaves something like "sox" <= tested it shortly with some voice samples - on command line its ok (with tempo between 0.75 to 1.5)
If this also not acceptable working with all files there are few chances it will be online SOON.

**Comment by Laterunner** [comment]
thank for the try :) - still hoping you proceed.
Kind regards Laterunner

**Comment by LocutusOfPenguin** [comment]
entered a flag to switch between 75% to 150% of normal speed (in 5% steps).
To make it work y need to install "sox" package.
Probl online with next version (testing now - but seems ok, so far)

**Comment by Laterunner** [comment]
thank you- sounds nice. I think speeding up the voice might be a good feature.
Kind regards
Laterunner

**Comment by LocutusOfPenguin** [comment]
with next release (v0.88) expected to be online beginning of next week this is finally solved.
Changed the factor again from 90% to 135% (with 5% steps) of standard speed.

**Comment by Laterunner** [comment]
:) excellent - Laterunner
