### ISSUE TITLE
Shutdown (self wired) Pi3B -  DGT3000Pi

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#236]
Hi I use the self wired DGT3000, Raspberry Pi3B with USB-Sound, Wlan and BT. Pi has a minmal and ipdated and upgraded Jessie and picochess is V87. Wiring was done as described by Locutusofpenguin.

Everything but shutdown works, but shutdown has a problem! With two Queens on d1 and e1 picochess says" good bye" and does not shut down." "systemctl status picochess" gives:
" ... Failed to start dgtpistandby.target : Operation refused, unit may not be isolated."

It seems that "dgtpistandby.service" has a problem. It was copied to "/etc/systemd/system" as described in the manual and chmod was also done as proposed.

"Sudo shutdown now" command entered manually shuts down and picochess can be restarted by switching on the DGT3000.

I also uncommented "dgtpi=true" and checked. In this case two queen shutdown works as it should.

Any Idea why two queen shutdown does not work in my DGTPi (V87)??

Kind regards

Laterunner

**Comment by LocutusOfPenguin** [comment]
These files (&system) made from Lucas. He once told me that:

26. Copy the system scrypts to using “sudo cp dgt/*.service dgt/*.target /etc/systemd/system”
27. Enable our startup message using “sudo systemctl enable dgtpi”
28. Enable picochess to startup automatically using “sudo systemctl enable picochess”

Perhaps that helps y.

**Comment by LocutusOfPenguin** [comment]
BTW...are y still using your odroid?
If yes, did y update to a jessie system there? => do y still need these scripts folder?

**Comment by Laterunner** [comment]
@LocutusOfPenguin : nice to hear from you. I shall look at your suggestions. Yes I still use the odroid. It is much faster than the Pi3 can well be used as a desktop, for YouTube, Internet and ....

I never managed to autoconnect the BT during startup,I always had to make the BT connection manually from the desktop and than start picochess from a terminal with "python3 picochess. py" or as a service. All Versions(up to 87) worked really fine after manual BT connection. 

I already downloaded an image with Jessie for Odroid and as soon as I find some time I shall install picochess onto this Jessie image just to find out if this solve the BT Problem.

Wiring the DGT 3000 directly to the Raspberry was a very good Idea, saves a lot of time to have the moves on the clocks display (Chessplayers cannot wait :) )

As you probably know the Odroids GPIO is not fully compatible with the Pi´sGPIO, a shifter shield is needed and still some Pins are different (Pin 35 is Power_on). It is therefore  impossible to wire the odroid for  DGTPi mode as you described. (I think a skilled programmer could probably redirect the pins easily, but I cannot do this). Maybe someone reads this and says: " oh that is easy ... .please tell me asap"
 
Kind regards Laterunner

**Comment by LocutusOfPenguin** [comment]
autoconnect prob. only working (well) if y go for Jessie. At least at PI. I expect the same for odroid. Therefore i asked y in a different issue (several months ago), to update to jessie, if possible.

Using the odroid wont work as it does with a rasp pi concerning getting a (dgt)Pi version, like y did now. The timing is different, and many more. So, the pins is not the only problem. It needs a complete rewrite of these C-files and i doubt someone will do it - i dont even have an odroid ;-)

**Comment by Laterunner** [comment]
Ok-  may shutdown works now at least the dgtPi shuts off. I also expected the Raspberry to shut down completely but ok it probably works as it should.
