### ISSUE TITLE
(three) comments on the manual, singers scripts and issue 145

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#238]
Hi, recently I had to reinstall picochess from the scratch. I Started with raspbian + pixel image on a Raspberry Pi3, with USB soundcard, monitor/mouse/lan and wLAN  connected.

Your Manual Installation description is just excellent!

But three small points are missing in the manual:

1. on a DGTPI (also on a self wired one) you need: "sudo cp dgtpistandby.target /etc/systemd/system"

This is missing in the manual V83 (6. Copy the dgtpi services into the correct place ....)

2. maybe you should also mention that for sound output the default sound card No (0 or 1) has to be entered in "usr/share/alsa/alsa.conf" . - You can find out the card number  to be entered with "aplay -l".

3. Maybe you should also mention that at the moment (MAi 2017) with Debian Jenny on Raspberry Pi3  it not possible to connect BT Speakers or BT headsets for audio. => You must use a wired connection! 

Bluetooth Audio  works perfect  with my odroid XU4 and I still use this machine. So please leave singers scripts also future Versions. The script are still very useful for non-Jenny installations.

I also found out, why I had those obsure connection problems with the DGT_BT_Board: The reason was an activated picochess.service at startup. After picochess.service was disabled I could connect the BT and start picochess without stopping and restarting picochess (python3 picochess.py- issue 145).

Kind regards Laterunner

**Comment by LocutusOfPenguin** [comment]
Thanks!
for 1) i changed it already.
for 2-3) i dont understand why that is needed/not working. I prefer to leave that out. For me seems to be a linux problem not a picochess one. When i setup a new jessie+pixel some time ago my sound coming out of the jack without any changing in software (f.e. alsa setup).

**Comment by LocutusOfPenguin** [comment]
with v0.9j we need Stretch to have c++14 (=> rodent3 engine)... I guess y get similar problems if you keep the old way (singers script). But i cant help with odroid.
Anyway, i close this issue now.
