### ISSUE TITLE
Move time display bug

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#244]
http://youtu.be/n9ybjganQSE

PicoChess 0.9f is not displaying the computer's thinking time when the user requests an alternative move. In this video the engine wants to play 3...d5 but the user requests an alternative move by pressing the middle button. After pressing this button the clock display remains at 0.00 for three seconds, but should rather count down from 0.03 to 0.00.

**Comment by LocutusOfPenguin** [comment]
Hi DJ,

thats what i said in my eMail (today)
Its only at movetime , and this display error (=0). Should be fixed already on MY master.

Jürgen

**Comment by LocutusOfPenguin** [comment]
it also happened on switch_sides
both solved now (online with v0.9g) including #245
