### ISSUE TITLE
Problem parsing d-rodent.uci

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#246]
PicoChess seems to have a problem with parsing `d-rodent.uci`.

This file contains the following personalities:
Anand, Anderssen, Botvinnik, Fischer, Larsen, Marshall, Nimzowitsch, Petrosian, Reti, Rubinstein, Spassky, Steinitz, Tarrasch.

However, when selecting a personality with the black Queen, the squares a5–h5 correspond to these personalities:
Anand, Botvinnik, Larsen, Nimzowitsch, Reti, Spassky, Tarrasch, Tarrasch.

So it seems that PicoChess is skipping every second personality and (when it sees that there are no more personalities left) doubling Tarrasch.

The same issue occurs after overwriting the contents of `d-rodent.uci` with, for example, the contents of `personality_school.uci`.

**Comment by LocutusOfPenguin** [comment]
Hi DJ,
that is not a "problem".
Picochess expects each level increasing in strength so it will try to distribute from first to last over the 8 fields in some distance.
Therefore we have this SF levels 0,3,6,...18,20 (here the distance is 3)
For Rodent this logic is -for sure- not successful. You can still use the buttons, to change to the others.

For the twice tarrasch, i prob. need to care this not happening. I'll take a look lateron.

Jürgen
