### ISSUE TITLE
Send max. one email per game

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#253]
I'd like to request a limit to the number of emails that PicoChess can send for every game (ideal limit: one). Normally, one would expect one single email for one single game. Currently Picochess can send multiple emails for one single game, as the following situation ilIustrates.

I was playing a 1'+1" Fischer game. The computer lost on time (clock display: "time") and PicoChess sent the game notation by email. I decided to continue playing, the computer received its 1" increment and started thinking. Again, it lost on time. The clock displayed "time" again and another email with the game notation was sent. And so on...

Perhaps this one can be tackled when the email is not sent immediately upon the end of the game (mate, draw, time control) but rather at the moment the user has put the pieces back to starting position?

**Comment by LocutusOfPenguin** [comment]
Hi DirkJan,
this is an OLD issue...The last time we (or me?) decided to call a "continue of an ended game" a new game..so, the behave of picochess is OK. I dont want to do a counter keeping how often i emailed it already (even thats easy to implement). If i change something there, perhaps as y suggest on other evens (like a newgame).

But im thinking about kick this "auto-email" out completely =>so y need to do something to get games emailed, like "click on clock buttons" similar to the webserver.
This ALL (also) has to do with my idea for #212 (even the connection is vague right now)
But its not decided and i dont have time for that right now ...so, y need to wait for any dev action there&here

**Comment by LocutusOfPenguin** [comment]
Another idea i have:
Perhaps i can implement a "plus 1min" feature on clock buttons - prob. by each side seperate.
This way y can give more time to the computer, and the same system runs again (well, if computer looses again on time, y will get another eMail - but as i said above, thats so cause correct).

This has the advantage, you can even use this function to setup times in normal games (at start!)...so its a more general function.
The disadvantage is : alot more work for me!

Please comment.
