### ISSUE TITLE
Picochess (Version 9l): Voice suddenly stops working

### ISSUE THREAD

**Issue by tosca07** [jromang/picochess#254]
Hello,

I use picochess v.9l on a dgt pi with Christina voice switched on.

Normally voice output works fine but it often occurs to me that during a longer game the voice output suddenly stops working (no other issue). 
Unfortunately I can’t replicate it every time but it seems to occur only in longer games when I almost have no time left. 

Furthermore it could have been caused when you often take back moves ;-) or if you have to correct the piece constellation but I have no figured out in detailed.

At least if I go onto the meine and switch the voice output off and on again it again works (at least until it again suddenly stops somewhere during the gameplay)

I try to figure out how to replicate this bug so that you can check but maybe you already have an idea what could be the cause?

Regards
Dirk

**Comment by LocutusOfPenguin** [comment]
Hi dirk
If one player has lower as 1 min rest time the voices are turned off

**Comment by tosca07** [comment]
Ah I See and it makes sense.

Thanks for the quick answer, Jürgen.

You can close this non issue ;~)

Regards and all the best for 2018 and I hope you will continue and still have fun to enhance picochess!
Dirk

**Comment by sshivaji** [comment]
We should document this behavior somewhere :)

**Comment by LocutusOfPenguin** [comment]
Yes  but it's done already in http://picochess.com/picochess-v0-9j-stretch/

**Comment by sshivaji** [comment]
Great. Can we also put it in manual?
