### ISSUE TITLE
Suggestion: rename some play modes

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#261]
This is not an issue but a suggestion.

I'd like to suggest to rename some play modes:

wQ square | current name | suggested name
---|---|---
a5 | Normal | Normal
b5 | **Brain** | **Ponder on** (or not a play mode?)
c5 | **Analyse** | **Best move**
d5 | **Kibitz** | **Score**
e5 | Observe | Observe
f5 | **Ponder** | **Kibitz**
g5 | — | —
h5 | Remote | Remote

Explanation:
* Brain mode ('permanent brain') is a solution for getting the engine behavior otherwise induced by setting UCI option 'ponder = True', so it seems logical to call it '**Ponder on**'. But I am also wondering whether this should be a play mode at all — couldn't this also be a clock setting and/or setting in picochess.ini?
* Analyse mode is showing the best move, so it could be called '**Best move**'.
* Kibitz move is currently showing the score, but not the best move. This is different from human kibitzer behavior, because human kibitzers usually also guess which move is coming next. So I think '**Score**' is a better name for this mode.
* Ponder mode has nothing to do with the UCI option 'ponder = True' but resembles human kibitz behavior. So I'd like to suggest to rename this mode to '**Kibitz**'.

**Comment by LocutusOfPenguin** [comment]
Hi DJ,

for this we would ask on forum. Its better to get a bigger user base (incl. dgt) before i rename them.

Jürgen

**Comment by djdekker** [comment]
Hi guys,
Thanks for commenting, I'll post this on the forum.
Greetings,
DJ
