### ISSUE TITLE
Ponder mode bug

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#262]
I had this position (White Kf6,Ra6, Black Kf8):
5k2/8/R4K2/8/8/8/8/8 w - - 0 1

In **Ponder mode** the clock correctly shows "mate in 1" and 1.Ra8#.

After carrying out 1.Ra8# the display briefly shows "mate", and then it should **stop** showing moves and evaluations (other than "mate"). Instead, the display incorrectly resumes the rotating display "Mate in 1" and 1.Ra8#.

In **Analyse mode** and **Kibitz mode** the clock correctly keeps displaying "mate" after carrying out 1.Ra8#.

**Comment by ScallyBag** [comment]
Confirmed, good spot
