### ISSUE TITLE
Speech output calls checkmate twice

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#266]
Today the engine checkmated me with the beautiful move 23...Qc1#.

Speech output was: "Queen c1. Checkmate. Black wins." and when I carried out Black's move on the board there was again speech output: "Checkmate."

So when the engine checkmates the user, there is twice "Checkmate" in the speech output.

Isn't the second announcement of "Checkmate" superfluous? I think it is sufficient for the clock to show "mate" without the voice repeating its earlier message.

**Comment by djdekker** [comment]
In the 1980s I used to play a lot against talking Elite A/S Challenger, the one introducing itself with its mechanical robot voice as: "I am Fidelity's Chess Challenger, your computer opponent". When checkmating the computer it would say for example: "From a6 to a8. Rook move. Check and mate. I lose." It was always nice to hear that! LOL

If I recall correctly, in such a case as the 23...Qc1# example (where the computer checkmates the human player) it would speak like this: "From d2 to c1. Queen move. Check." and after carrying out this move it would say: "Checkmate." Perhaps that's an idea for PicoChess?

**Comment by ScallyBag** [comment]
I still have my Voice Challenger 10, maybe I should record it for use on PicoChess 😄

Al.

**Comment by LocutusOfPenguin** [comment]
Qc1# might be beautiful but "23." is not :-)
Elite A/S...wow, i also had an Elite A/S Budapest and i really like the voice alot!

Back to yr issue:
Perhaps its best to delay the GAME_END event until y really do this move on board (BEST_DONE event instead of BEST_SHOW event). That would also eMail yr game after y done it, not like now, as soon picochess is pushing out its move.

Al:
yes, perhaps ....but i prefer it talking french :-)

**Comment by LocutusOfPenguin** [comment]
it should be done in the following way:

1. picochess say "Qc1 check(mate)" as soon the move is displayed. That includes other game ending texts like "stalemate", "repetition" etc.
2. the game result "white/black wins", "draw", "time lost + X wins" after the move is done on board
3. in case of a "set pieces" repeat 1)

**Comment by LocutusOfPenguin** [comment]
fixed this on my versions v0.9P/Q
