### ISSUE TITLE
Time does not count down in per move time control

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#27]
Machine is setup to respond at 10 seconds per move. When thinking, display shows 10:00, not counting down. After ten (more like twelve, btw) seconds it responds with a move normally.

This mode (sec per move) seems not to be affected by that other "Time" timout bug.
Here's a video:
http://youtu.be/5W3Hyua0m2g

**Comment by ifekali** [comment]
Timer still not counting down in time-per-move time controls. Just reminding :)

**Comment by LocutusOfPenguin** [comment]
Talked to Jonas directly. For me, never had this problem.
Can someone else please check, if this issue is on clock, maybe?
Thanks!
