### ISSUE TITLE
Picochess halts after selecting No Book

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#31]
Picochess will not respond to e4 after selecting "Nobook". (It still responds to Level & Book changes, but will not move until reboot.)

**Comment by LocutusOfPenguin** [comment]
still open, isnt it?
I would fix it by creating an empty "0-nobook.bin" file and make library = [] in "get_opening_books"
avoiding if statements somewhere else;-)

**Comment by sshivaji** [comment]
Just now fixed in master. @LocutusOfPenguin, thanks for the suggestion, I have used that.
