### ISSUE TITLE
Chess 960 implementation

### ISSUE THREAD

**Issue by Frits-Support** [jromang/picochess#39]
Is there a schedule or plan to implement Chess960 into the PicoChess software ?

**Comment by LocutusOfPenguin** [comment]
What shiv said is correct. I updated the code abit to take into account the special castling rules chess960 has.

There are some limits coming from "setup pos", like missing EP square, moved before R,K => cant castle anymore even the pieces are at correct place.

AND (in chess960 mode):
only inner rook has the right for castle like Ke1,Rg1,Rh1 and the Rh1 isn't allowed for castle (moved before). This i *won't* fix.

issue to be closed soon.
