### ISSUE TITLE
Confirmation sound when executing correct computer move

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#41]
At this time (ver. 0.30) Picochess beeps when engine shows a move on display, but not when user executes said move. Beeping again when user executes *correct* move would help avoid entering a wrong move (thus halting Picochess).

All the beeping might prove annoying to some (I love it) and should probably be switchable in settings.

**Comment by djdekker** [comment]
A very good idea to make beeping switchable! I'd love to be able to switch off all clock sounds when I'm playing chess late at night and all others in the house are sleeping... The constant beeping is extremely annoying to them (and to me as well, BTW).

**Comment by Frits-Support** [comment]
Very nice feature. 
Any idea when the 0.32 will be available on the web for updating my PicoChess?

**Comment by ifekali** [comment]
My plan was to release the image for 0.33 with bug fixes (some of the used-to-be-working features are still broken in 0.32) that Shiv promised  "over the weekend".


> On 19. mar. 2015, at 14.14, Frits-Support <notifications@github.com> wrote:
> 
> Any idea when the 0.32 will be available on the web for updating my PicoChess?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by Frits-Support** [comment]
Thank you Jonas, I will wait.

Do you have a list of bugfixes in this version or will it be published in Github?

Kind Regards,
Frits Jansen
DGT Technical Support

Van: Jonas Žnidaršič [mailto:notifications@github.com]
Verzonden: 19 March 2015 14:26
Aan: jromang/picochess
CC: Frits Jansen | DGT
Onderwerp: Re: [picochess] Confirmation sound when executing correct computer move (#41)

My plan was to release the image for 0.33 with bug fixes (some of the used-to-be-working features are still broken in 0.32) that Shiv promised "over the weekend".


> On 19. mar. 2015, at 14.14, Frits-Support <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Any idea when the 0.32 will be available on the web for updating my PicoChess?
>
>

-
Jonas Žnidaršič
jonas@jonas.si<mailto:jonas@jonas.si>

**Comment by ifekali** [comment]
The bugs are listed on Github, yes. Shiv should know more about which ones will get squashed first ...

> On 19. mar. 2015, at 14.32, Frits-Support <notifications@github.com> wrote:
> 
> Do you have a list of bugfixes in this version or will it be published in Github? 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by jromang** [comment]
This is already implemented with the last 'voice' patch : https://github.com/jromang/picochess/commit/0c9fb84230f1850bbcaa191767252bc8d83e053c
There is a disable beep option :-)
