### ISSUE TITLE
Book move confirmation

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#47]
When (immediately after) user makes a book move, some confirmation in display should be possible. (Some versions ago, Pico displayed "Book" for a moment.) A line in .ini file disables this for purists.

Very useful when trying to learn book openings, user can takeback immediately when out of the book  trying to follow it.

**Comment by LocutusOfPenguin** [comment]
Can be also closed, after my last pull request ... Updated "on the fly"

**Comment by sshivaji** [comment]
Closed with latest pull
