### ISSUE TITLE
Bluetooth connection garbled when using XL clock

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#51]
Bluetooth board only works via USB when using old XL clock. When connecting via bluetooth, Picochess reacts to first move (is aware of board), but halts immediately thereafter.

OTOH, connection to Revelation II chessbot (remember, it emulates the XL clock and *only* connects via bluetooth) seems normal, works.

**Comment by LocutusOfPenguin** [comment]
isn't this solved (now)? Esp. after your video.
