### ISSUE TITLE
Wrong clock display when picochess checkmates user

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#59]
When Picochess checkmates the user, the clock does not display the final move. Instead, the clock displays 0:00 (or sometimes some strange time like 1:07:23), pauses for a couple of seconds and then displays 'MATE'. Then, if the user guesses the correct move and performs it on the board, the clock very briefly displays 'OK' and then resumes its countdown (although the game is already over).

Picochess 0.33 on Raspberry Pi 2
DGT BT Board/3000 Clock

**Comment by sshivaji** [comment]
I will work to fix it this weekend, I thought it was already resolved. Thanks

**Comment by djdekker** [comment]
It is resolved in the master branch, but not in the stable branch ;)
