### ISSUE TITLE
Add option to chesstalker to support short notation

### ISSUE THREAD

**Issue by gambcl** [jromang/picochess#62]
Some people have requested support for short notation for chesstalker, so saying "a3" instead of "Pawn a2a3".

We could add the following config options to allow users to choose their preferred style of speech:
computer-voice = long/short
user-voice = long/short

The chesstalker engine and vocabulary would need updating to handle both long and short styles.

**Comment by ifekali** [comment]
I suggest keeping the true/false convention.

For example, I'm quite unhappy with the latest ...

disable-dgt-clock-beep

... setting. It should be:

dgt-clock-beep = true/false.

I propose:

short-notation-voice = true/false

or something similar.



> On 11. apr. 2015, at 13.16, Charles Gamble <notifications@github.com> wrote:
> 
> We could add the following config options to allow users to choose their preferred style of speech:
> computer-voice = long/short
> user-voice = long/short
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by sshivaji** [comment]
I missed this issue altogether. I modified the chess talker code of Charles to speak moves in shorter notation (just changed a few lines). I have left the longer notation as a code comment. If this shorter notation works for everyone then we can keep as is, if people want to have a choice, it is worthwhile to add a flag to support both.

**Comment by sshivaji** [comment]
Charles, have a look and let me know if you want to keep the code as is or change. Thanks

**Comment by gambcl** [comment]
The only thing I would say is that part of the design of the chesstalker module was to try to keep all actual speech syntax strings in the vocab files, so that they can be customised per voice if necessary, and it looks like there is now some hard-coded strings in the code itself.

I was planning to add the configuration flag and maybe extend/change the vocab to support both long/short notation, I just haven’t got around to it yet.
If people are really wanting it I can try to get it done this week.

Charles

**Comment by ifekali** [comment]
Choosing short/long voice notation in settings is surely nice, but it certainly is not critical, as it is hard to imagine a user that would need/want the voices speaking in long notation. I cannot imagine a scenario where long notation would be needed.


> On 15. jun. 2015, at 14.55, Charles Gamble <notifications@github.com> wrote:
> 
> I was planning to add the configuration flag and maybe extend/change the vocab to support both long/short notation, I just haven’t got around to it yet.
> If people are really wanting it I can try to get it done this week.

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by sshivaji** [comment]
Charles, I see your point. With my quick implementation, supporting another spoken language or voice customization won't be easy. I chose a solution with low lines of code but lost flexibility.

If u are planning to rework this, submit a PR and we can incorporate.

**Comment by sshivaji** [comment]
Meanwhile, I will try to clean up my change to use speech strings.
Apologies for not realizing this..

**Comment by LocutusOfPenguin** [comment]
Hi,
this issue is now 1year old, and i dont see any resources of a developer to do it.
Also i would like to exchange chesstalker (since there is issue #154 providing a better talking system).

This issue be closed very soon. Sorry.
