### ISSUE TITLE
adding option -V/--version

### ISSUE THREAD

**Issue by lionping** [jromang/picochess#70]
since I was to dumb (but also too short of time) finding out how to create myown branche of picochess-master, maybe this is a way ;-) (and sorry... do I have to fork picochess?)

('d liked to ask picochess.py (on a bash cmdline) what picochess-version that is, and for this purpose there was only one line needed to be added to the "parser.add_argument"-block of picochess.py, namely

parser.add_argument("-V", "--version", action='version', version='%(prog)s version {}'.format(version), help="show current version", default=None)

"version" comes from utilities.py

**Comment by jromang** [comment]
Yes you have to fork and send a pull request (https://help.github.com/articles/using-pull-requests/) :-)

**Comment by LocutusOfPenguin** [comment]
to be consistent with other programs should be "-v" not "V"
