### ISSUE TITLE
Last move creating MATE

### ISSUE THREAD

**Issue by BenDGT** [jromang/picochess#72]
If PicoChess creates a MATE, the last move of the computer will not be displayed.
Suggestion is to toggle between displaying the move and displaying MATE

**Comment by djdekker** [comment]
This is issue #59.

There is a workaround until this issue is fixed: press the left clock button and Picochess will show the checkmating move -- this works on my DGT 3000 clock.

**Comment by BenDGT** [comment]
Dear Jean-Francois,

Thanks,

Ben Spenkelink
Project Manager Product Development
email: ben.spenkelink@dgt.nl
Digital Game Technology, www.DGTprojects.com, telephone +31 (0) 53 4305195 or 06 36139466
address: DGT B.V. , Hengelosestraat 66, 7514 AJ Enschede, The Netherlands
[cid:image001.png@01D09145.1171DC70]
