### ISSUE TITLE
Display a warning on illegal move in Observe mode

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#76]
When entering illegal move, Observe mode should display a warning with a beep.

**Comment by LocutusOfPenguin** [comment]
I missing this not only on observe mode....I think should also warn in normal mode

**Comment by LocutusOfPenguin** [comment]
I think, that's a double ticket.
Anyway, its - like said there - not easy to know, if its a wrong move - we only know if its a valid move (which has to do with the dgt-board-hardware). Ticket #100 is best, y can get..sorry
