### ISSUE TITLE
Email PGN on Button Press

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#80]
Most of games against the picobot end with user resigning, but to get PGN emailed, one must play to mate. This is a drag.

I propose PGN is emailed on some clock button press or menu choice. Documented in the docs.

Many thanks!

-Izmet Fekali

**Comment by ifekali** [comment]
DGT software uses placing two kings on adjacent center squares (an illegal position), if on white squares, White won, if on different colors, it's a draw.

I propose this as an alternative request for PGN fetch, and it signals End of Game to transcription and the result. (1:0)
This convention would be very welcome as tournament players are used to it, no?

**Comment by ifekali** [comment]
Interestingly enough, now that I have email PGN forwarding enabled, I noticed incoming emails ... PGNs are apparently sent on "New game", so there is no need to play to a mate.

However, there is no game result in the generated PGN, so maybe indicating it per DGT convention (see my comment above) is not a bad idea afterall.

Also, button press on the clock is therefore not really needed. (But indicating result probably is.)

**Comment by LocutusOfPenguin** [comment]
closed by #119
