### ISSUE TITLE
add used time per move to pgn

### ISSUE THREAD

**Issue by raimarHD** [jromang/picochess#85]
Hey,

it would be nice if the time usage is written to the pgn file. The pgn definition in 2001 has created the special "%emt" tag (elapsed move time) for that. http://www.enpassant.dk/chess/palview/enhancedpgn.htm

The definition:
4.4 Elapsed Move Time : the emt command

{[%emt 0:05:42]}

The elapsed time that a player used for the commented move. Takes one parameter in the format h:mm:ss

Do we have that information about time usage available? 

Best,
Raimar

**Comment by sshivaji** [comment]
Yes, it is available (can be computed).

Shiv

**Comment by ifekali** [comment]
This should be settable in the .ini. (I for one have no use for this and would be obsessively deleting these comments when archiving to my database :))

**Comment by LocutusOfPenguin** [comment]
Sorry - seems no dev has time to implement this. Gonna close this issue soon. Last call,
