### ISSUE TITLE
Stockfish 6 OR picochess not finding a mate

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#87]
Im not sure if this is an issue for Stockfish or picochess

The Position (white) Kc6, Bb7, Pd6 (black) Kb8, Rg4, Pc7
Its a forced mate in 2: d6xc7+ Ka7, c8N ++
but i always get c8Q?, or Ba6 which leads to draw by Rc4+

**Comment by ifekali** [comment]
> On 28. maj 2015, at 10.34, Jürgen Précour <notifications@github.com> wrote:
> 
> The Position (white) Kc6, Bb7, Pd6 (black) Kb8, Rg4, Pc7
> Its a forced mate in 2: d6xc7+ Ka7, c8N ++

2...Kb8 looks like a draw ...

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
ups...right!
So, everything ok, and i take some chess lessons (from picochess) ;-) Close
