### ISSUE TITLE
python-chess V0.8 UCI engine

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#89]
Hi,
on my fork (branch), i updated to V0.8 uci python-chess (=>uci.py).

For me, the code looks more clearer, but i'm not an expert in python at all => so no pull request.

Perhaps someone can take a look (for me, the software is running well, despite the logfile looks abit different to before).

Btw. Next i will implement the "second button, display ponder move"

How to talk to the software-leaders? Is this here the right place? I want to discuss about the future of picochess, like "menu", "playing modes", "display the eval", mainly stuff i wish most, and dont know how to implement it in correct python/picochess way.
Updating this to V0.8 is my path to the new futures (i wish to implement, or see implemented).

**Comment by sshivaji** [comment]
Sure, you can talk to the “software-leaders” here :)

I wanted second button to be ponder move or book move. I am going to look at buttons this weekend too and can help refactor. I am also going to add in more functionality to the web interface (as my next TODO after cleaning up buttons and menus). If you have a specific thing you want to do, feel free to email me or update on github (my email is sshivaji@gmail.com). We had a devs@picochess.org email address. We can add you to devs. Jean, do you know how to do this?

We had menu, playing modes, displaying eval and all working before. It might simply be a matter of copying it from the old repo which had everything! - https://github.com/jromang/Stockfish/tree/pycochess_dgt <https://github.com/jromang/Stockfish/tree/pycochess_dgt>

Keep us updated, thanks!

**Comment by LocutusOfPenguin** [comment]
Fine.
As mentioned, i did something for the "second button" this evening.
For me the most important thing was "setup pos". Its working now.

Next important step would be "analyse game", like play moves, see picochess tell me the best move, and value very few secs during i play over a game. That's what i hope to have soon ;-)

When this two working, it was worth to buy the board.
For this ill take a look at the (for me!) new github adress. But im not sure, i (personally) can implement it in a good python way (i'm a php programmer)


Despite that, i have alot of ideas to make it working better in some way. But this should be discussed with the "leaders" (long story - so not now & here), ha.

**Comment by sshivaji** [comment]
We had analyze game functionality before in the old tree. Don't worry that
much about ideal pythonic style, we can adjust that later. Currently, we
should aim to get features on the table and we can refactor/update python
styles later.

We are the so-called "leaders" :) I think its ok to send ideas like a
roadmap to the forum and/or to devs@picochess.org

I will keep testing the new features and give feedback as well (just like
Jonas).

**Comment by LocutusOfPenguin** [comment]
@sshivaji 
Pls close this also #47 (thats also done with my pull-request)
