### ISSUE TITLE
Note the Level into PGN output

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#90]
When emailing the PGN file, Picochess inserts user name culled from the email address, this is very cool. (But maybe it could capitalize it?)

For the machine, it simply uses "PicoChess". I propose changing this to "Stockfish" (or whatever engine is being used) with added Level of play, i. e. "Stockfish Level 11". (I usually do this manually when archiving my games into database.)

**Comment by LocutusOfPenguin** [comment]
I'll fix it , including #15 (soon)

**Comment by ifekali** [comment]
You are da man!

> On 22. jun. 2015, at 18.07, Jürgen Précour <notifications@github.com> wrote:
> 
> I'll fix it , including #15 (soon)
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
I see the Level in web interface username now, but parentheses mess up the PGN when downloaded (my HIARCS explorer gets confused.)

Also, there's no Level noted in emailed PGN. (Again, I'm guessing parentheses are at fault probably.)

**Comment by ifekali** [comment]
The parentheses are not at fault, I found.
"Level 0" gets output into BlackELO field now, but my database manager (HIARCS) expects a numerical  field there, not ASCII, messing it up ...
