### ISSUE TITLE
Restarting picochess via buttons on clock

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#95]
A suggestion:

As the code is still buggy in some modes (kibitz mode stalls sometimes, some menus still work but there's no way to star over), a way to reset Picochess via a simultaneous two button press on clock (and/or using special illegal position on board like four queens in the centre and the rest of the pieces in starting position?) would be very welcome. Picochess should restart and maybe with another two button press (and special position like two black queens on d8 and e8) reboot.

**Comment by puba** [comment]
Once when clock freezes and that happens quite a lot, especially when switching between modes, it is impossible to bring it back to life again, as dgt board also, the same, both dead as last winter. But still good idea, worth a try.

**Comment by LocutusOfPenguin** [comment]
Do you have a path how to crush it by (for example) switching between modes?
I guess the modes switch is not 100% bullet proved - but i can fix it (with path its easier).

**Comment by puba** [comment]
Not sure if that can be done in the first place, though. In-vivo game switching between default mode and for example observe mode causes instant freeze.

**Comment by LocutusOfPenguin** [comment]
what does "in-vivo" mean?

**Comment by puba** [comment]
experimenting while playing at the same time:)

**Comment by puba** [comment]
In game switching between modes causes situation seen on video

https://youtu.be/HBlqpEdfXMw

**Comment by djdekker** [comment]
This video won't be displayed as it is set to "private".

**Comment by puba** [comment]
sry, fixed

**Comment by LocutusOfPenguin** [comment]
as far i can see:
y entering "position" , then press button4 (twice), and i seems to crush.

I'll take a short look tomorrow morning (with board), if that's the case. Otherwise try the whole sequence.

**Comment by ifekali** [comment]
No, pico is *already* in unstable state at the start of the video. We don't know what was done to enter this state.

At the end, he is asking for a way to reboot/restart pico with extra queens.

> On 18. jun. 2015, at 22.09, Jürgen Précour <notifications@github.com> wrote:
> 
> as far i can see:
> y entering "position" , then press button4 (twice), and i seems to crush.
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by puba** [comment]
The whole freeze sequence step-by-step 
https://youtu.be/g0WxZFNypEY

**Comment by LocutusOfPenguin** [comment]
@puba 
after Rb1, its black turn...and you play f2f3, c6c5 ..or do i miss something? => illegal moves.

If you using "pos setup" after rb1, you prob. catch the error from #104.
I can't see, what you clicking on the clock.

Btw, i just updated the code, to address this setup error (not 100% functional).

**Comment by ifekali** [comment]
Indeed, he is moving with White twice.

> On 19. jun. 2015, at 14.56, Jürgen Précour <notifications@github.com> wrote:
> 
> after Rb1, its black turn

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by puba** [comment]
My bad, no excuse for that; but freeze still there, when jumping from one mode to another; got to play just default or just analyse or just observe and not default and analyse or default and observe else pico freeze

**Comment by LocutusOfPenguin** [comment]
On "system" menu is now (v0.51) a "reboot" & "halt" => issue closed
