### ISSUE TITLE
Voices voice after user's move only (ver. 0.41)

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#97]
Silent when pico moves, but then *two* moves are announced after user's move.

This bug was introduced with 0.40 or 0.41 (not sure), as voices behave normally in 0.39.

**Comment by puba** [comment]
Start delay is no more there, gone in the latest master branch, but there is no sound when picking the side to play(black, white) and game modes(game, analysis....). Got to check chesstalker.py. And yes, voices on default game mode are not synced with clock, for example, when user makes a move, clock stops, but move is displayed and said only when computer makes his.  Distracting and confusing.

**Comment by ifekali** [comment]
Are you sure? I'm still getting the stall on the master branch ... Just tested thrice right now ... 

> On 14. jun. 2015, at 11.02, puba <notifications@github.com> wrote:
> 
> Start delay is no more there, gone in the latest master branch, 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by puba** [comment]
Try choosing game level and time control before making first move....

**Comment by ifekali** [comment]
As before, the game modes and levels can be set, but it doesn't respond to first move still

> On 14. jun. 2015, at 11.46, puba <notifications@github.com> wrote:
> 
> Try choosing game level and time control before making first move....
> 
> 

Kakšen username že maš na twitterju?

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by puba** [comment]
@traburg

**Comment by LocutusOfPenguin** [comment]
i fixed it...but my branch is NOT ready for pull (right now)

**Comment by puba** [comment]
<a href="http://www.freesmileys.org/smileys.php" title="Smiley"><img src="http://www.freesmileys.org/smileys/smiley-think004.gif" alt="Smiley" border="0" /></a>
